In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pbn_37k
from pbn_37k.ask import sigAssistant

import pandas as pd
from tqdm import tqdm
tqdm.pandas()

from dotenv import load_dotenv
load_dotenv()

brain = sigAssistant(pathCache=".cache/", llm_highend="gpt-4o",  llm_fast="gpt-4o-mini")

/home/kelu/projets/gbnexplore/.venv/lib/python3.11/site-packages/langchain/embeddings/cache.py:58: UserWarning: Using default key encoder: SHA-1 is *not* collision-resistant. While acceptable for most cache scenarios, a motivated attacker can craft two different payloads that map to the same cache key. If that risk matters in your environment, supply a stronger encoder (e.g. SHA-256 or BLAKE2) via the `key_encoder` argument. If you change the key encoder, consider also creating a new cache, to avoid (the potential for) collisions with existing keys.
  _warn_about_sha1_encoder()

In [4]:
from langchain_community.chat_models import ChatPerplexity
from langchain.globals import set_llm_cache
from langchain_community.cache import SQLiteCache
from langchain_perplexity import ChatPerplexity


import pandas as pd
set_llm_cache(SQLiteCache(database_path=".cache/.langchain.db"))

In [5]:
perplex = ChatPerplexity(model="sonar-pro")

def askp(prompt, size="low"):

    chat = perplex
    response = chat.invoke(prompt,
                            extra_body={"web_search_options":
                                        {"search_context_size": size}}
    )
    x = response.model_dump()["content"]
    citations = response.model_dump()['additional_kwargs']["citations"]
    for n in range(len(citations)):
        x = x.replace("["+str(n+1)+"]", "(src: "+citations[n]+" )")
    return x

In [6]:
## Finding similar use cases.

prompt_template = """We are reviewing the use case of a product or service to be delivered in a GBN (green building neighorhood).
This use case takes place in the city of {Place}.

Given the following case studies description

--- 

{use_case}

--- 


You have to find me five other similar case studies that have been implemented in other similar cities, and provide as much detail as you can.

The city must be in Europe. It'd be better if we can refer to another horizon / european project for the two last case studies.

Clearly indicate the title and the number of the case studies you will find in your answer.

DONT refer to the original use case, only provide new case studies. Don't use case studies from the EU H202020 project called PROBONO.


## X. Title (replace with actual title of the case study))

* **Case study Title:** title
* **Location:** City, Country

### **Description**

description  
 
###  **Key Features:**  

- **Technology Used:** technology  
- **Sustainability Impact:** impact  
- **Implementation Challenges:** challenges  
- **Outcomes:** outcomes


### **Parallels to the use case being reviewed**  

- first parallel 
- second parallel
- etc

### **Social, Economic, Environmental Benefits:**
- first outcome 
- second outcome
- etc

"""

In [15]:
original_use_cases = pd.read_parquet("data/pbn/uc.parquet.gzip").drop_duplicates(subset=["Source"])[["Origin","Place","Type","Source","Source_Title"]].reset_index(drop=True)
NUC = len(original_use_cases)
print(NUC)
original_use_cases.head(3)

49

,Origin,Place,Type,Source,Source_Title
0,ZP_UCS--DUB-D-UC1,Dublin,UC,# Use case : DUB-D-UC1\n\n\nCity: Dublin\n\n##...,Dublin energy monitoring and management.
1,ZP_UCS--PTO-B-UC1,Porto,UC,# Use case : PTO-B-UC1\n\n\nCity: Porto\n\n## ...,Operational efficiency and sustainability impr...
2,ZP_UCS--MDC-B-UC1,Madrid,UC,# Use case : MDC-B-UC1\n\n\nCity: Madrid\n\n##...,Electricity monitoring and sustainability repo...

In [16]:
limit = NUC+1

content = []
for ix, row in original_use_cases.head(limit).iterrows():
    prompt = prompt_template.format(use_case=row["Source"], Place=row["Place"])
    response = askp(prompt, size="low")
    print(f"# Use case from {row['Origin']}\n")
    print(response)
    print("\n"+"-"*80+"\n")
    content.append({
        "Origin": row["Origin"],
        "Place": row["Place"],
        "Type": row["Type"],
        "Source": row["Source"],
        "Source_Title": row["Source_Title"],
        "Similar_use_cases": response
    })
df = pd.DataFrame(content)

NameError: name 'prompt_template' is not defined

In [9]:
prompt_detail_template = """You are reviewing a list of case studies related to green building neighborhoods (GBN) implemented in various European cities.
Have a look at the high level review of the following case study:

{case_study}



## Action for you:

Provide three pages, as complete as possible, about the details of this case study.

Use the following structure:

```
# [Official name of the project/program]

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information**
- **Initiative Title:** [Official name of the project/program]
- **Alternative Names:** [Any other names by which the initiative is known]
- **Location:** [City, Neighborhood/District, Region, Country]
- **Geographic Coordinates:** [If relevant for mapping purposes]
- **Timeline:** [Start date, key milestones, completion/ongoing status]
- **Project Scale:** [Size in area, population affected, or investment value]
- **Leading Organization(s):** [Government agencies, private developers, NGOs, or partnerships]
- **Funding Sources:** [Public, private, PPP, international aid, etc.]

### **Executive Summary**
Provide a 200-300 word overview that captures the essence of the initiative, its primary objectives, and its significance in the urban development landscape.

---

## **II. CONTEXTUAL ANALYSIS**

### **Urban Context**
- **City Profile:** Describe the host city's population, economic base, geographic characteristics, and position within regional/national urban hierarchy
- **Neighborhood/District Characteristics:** Detail the specific area where the initiative is located, including:
  - Historical development patterns
  - Current land use composition
  - Demographic profile (income levels, age distribution, ethnic/cultural composition)
  - Existing infrastructure quality and accessibility
  - Environmental conditions and constraints

### **Pre-Initiative Conditions**
- **Problems/Challenges Identified:** What specific urban issues was this initiative designed to address? (e.g., inadequate housing, traffic congestion, environmental degradation, economic stagnation, social inequality)
- **Triggering Events:** Were there specific catalysts that prompted action? (e.g., natural disasters, economic crises, policy changes, community mobilization)
- **Stakeholder Landscape:** Who were the key actors and what were their interests before the initiative began?

### **Policy and Regulatory Environment**
- **Governance Framework:** What governmental structures and authority were involved?
- **Relevant Policies:** Which urban planning policies, zoning regulations, or development strategies shaped the initiative?
- **Legal and Institutional Enablers/Barriers:** What legal frameworks facilitated or complicated the initiative?

---

## **III. INITIATIVE RATIONALE AND OBJECTIVES**

### **Strategic Vision**
- **Primary Goals:** What were the explicitly stated objectives of the initiative?
- **Vision Statement:** What aspirational future was the initiative working toward?
- **Alignment with Broader Plans:** How did this fit into citywide, regional, or national development strategies?

### **Problem-Solution Logic**
- **Theory of Change:** Explain the causal pathway from initiative activities to intended outcomes
- **Target Beneficiaries:** Who was intended to benefit, and how?
- **Innovation Elements:** What made this approach distinctive or experimental?

### **Drivers and Motivations**
- **Political Drivers:** Election cycles, political leadership priorities, public pressure
- **Economic Drivers:** Investment opportunities, economic development needs, market demands
- **Social Drivers:** Community advocacy, equity concerns, quality of life improvements
- **Environmental Drivers:** Climate adaptation, sustainability goals, resource management
- **Technological Drivers:** Availability of new technologies or smart city trends

---

## **IV. DESIGN AND IMPLEMENTATION APPROACH**

### **Project Design**
- **Conceptual Framework:** What urban design principles, planning philosophies, or development models guided the initiative?
- **Physical/Spatial Design:** Describe the built environment changes, infrastructure investments, or spatial reorganization involved
- **Scope and Phasing:** How was the project structured and sequenced over time?

### **Technologies and Innovations**
- **Technologies Deployed:** List and describe specific technologies used (e.g., smart sensors, renewable energy systems, digital platforms, construction techniques)
- **Innovation Type:** Classify innovations as technological, social, financial, governance-related, or process-oriented
- **Integration Approach:** How were technologies integrated with existing urban systems?

### **Implementation Methodology**
- **Procurement and Contracting:** How were implementers selected and engaged?
- **Stakeholder Engagement:** Describe the process for involving residents, businesses, and other stakeholders
- **Participatory Elements:** What opportunities existed for community input and co-creation?
- **Project Management:** What structures and processes were used to coordinate activities?

### **Financing Model**
- **Budget and Costs:** Total investment, cost breakdown by component
- **Funding Mix:** Proportions from different sources
- **Revenue Mechanisms:** User fees, tax increments, land value capture, or other financing innovations
- **Financial Sustainability:** Plans for long-term financial viability

---

## **V. CHALLENGES AND ADAPTIVE RESPONSES**

### **Implementation Challenges**
- **Technical Challenges:** Engineering difficulties, technology failures, infrastructure constraints
- **Financial Challenges:** Budget overruns, funding gaps, economic downturns
- **Social and Political Challenges:** Community opposition, political interference, displacement concerns, equity issues
- **Administrative Challenges:** Bureaucratic delays, coordination problems, capacity constraints
- **Environmental Challenges:** Unforeseen environmental impacts, climate events, site contamination

### **Adaptive Strategies**
- **Problem-Solving Approaches:** How were challenges addressed?
- **Design Modifications:** What changes were made to original plans?
- **Lessons Learned During Implementation:** What insights emerged that shaped the project's evolution?

---

## **VI. OUTCOMES AND IMPACTS**

### **Direct Outputs**
- **Physical Outputs:** Infrastructure created, buildings constructed, land developed
- **Service Delivery:** New or improved services provided to residents
- **Quantitative Metrics:** Numbers served, area covered, capacity created

### **Social Impacts**
- **Community Benefits:** Improvements to quality of life, health outcomes, safety, social cohesion
- **Equity Outcomes:** Distribution of benefits across different social groups, effects on vulnerable populations
- **Displacement and Gentrification:** Any unintended negative consequences for existing residents
- **Social Capital:** Changes in community networks, civic engagement, or social trust
- **Cultural Impacts:** Effects on cultural heritage, identity, or creative expression

### **Economic Impacts**
- **Job Creation:** Direct and indirect employment effects
- **Economic Activity:** Business development, investment attraction, productivity gains
- **Property Values:** Changes in real estate markets
- **Cost Savings:** Efficiencies or reduced expenses for residents or government
- **Economic Inclusion:** Effects on poverty, income inequality, or economic opportunity

### **Environmental Impacts**
- **Climate and Emissions:** Changes in greenhouse gas emissions, climate resilience
- **Resource Management:** Water, energy, material use efficiency
- **Environmental Quality:** Air quality, noise, green space, biodiversity
- **Waste and Pollution:** Improvements or deteriorations in waste management or pollution levels
- **Sustainability Metrics:** Performance against environmental standards or certifications

### **Governance and Institutional Impacts**
- **Institutional Capacity:** Strengthened government capabilities, new collaborative mechanisms
- **Policy Influence:** Inspiration for new policies or regulations
- **Transparency and Accountability:** Improvements in governance quality

### **Performance Against Objectives**
- **Success Metrics:** To what extent were stated objectives achieved?
- **Unintended Consequences:** Positive or negative outcomes not originally anticipated
- **Long-term Viability:** Evidence of sustainability and lasting impact

---

## **VII. TRANSFERABILITY AND BROADER RELEVANCE**

### **Replicability Assessment**
- **Contextual Dependencies:** Which elements were unique to the local context vs. potentially transferable?
- **Critical Success Factors:** What conditions or elements were essential to positive outcomes?
- **Scalability:** Could this approach work at different scales?

### **Comparative Analysis**
- **Similar Initiatives:** How does this compare to analogous projects in other locations?
- **Best Practices:** What elements represent exemplary practice in urban development?
- **Cautionary Lessons:** What should others avoid or approach differently?

### **Parallels to [Your Specific Use Case]**
*[This section should be customized based on the specific project or context you're comparing to]*
- **Contextual Similarities:** Shared urban conditions, challenges, or opportunities
- **Methodological Parallels:** Similar approaches to planning, implementation, or engagement
- **Technological Overlaps:** Common technologies or innovation strategies
- **Stakeholder Dynamics:** Comparable governance structures or partnership models
- **Transferable Strategies:** Specific lessons or approaches applicable to your context
- **Adaptation Considerations:** What would need to change to apply insights from this case?

---

## **VIII. CRITICAL ASSESSMENT AND REFLECTION**

### **Strengths of the Initiative**
Identify and explain the most successful or commendable aspects of the project.

### **Limitations and Weaknesses**
Honestly assess shortcomings, missed opportunities, or problematic elements.

### **Equity and Justice Considerations**
Evaluate whether the initiative advanced or hindered urban equity, environmental justice, and inclusive development.

### **Future Outlook**
- What is the long-term trajectory for this initiative?
- What ongoing challenges or opportunities exist?
- What evolution or next phases are planned or needed?

---


 **ANALYSIS INSTRUCTIONS**

When analyzing an urban development initiative using this framework:

1. **Be Comprehensive**: Address all sections thoroughly, noting when information is unavailable
2. **Be Evidence-Based**: Support claims with specific data, examples, or credible sources
3. **Be Critical**: Move beyond promotional descriptions to assess real impacts and trade-offs
4. **Be Contextual**: Always situate the initiative within its specific urban, political, and social context
5. **Be Comparative**: Draw connections to similar initiatives and broader urban development trends
6. **Be Forward-Looking**: Consider implications for future urban development practice
7. **Maintain Objectivity**: Present multiple perspectives, especially on controversial aspects
8. **Highlight Complexity**: Acknowledge that urban development outcomes are rarely purely positive or negative

The goal is to produce a nuanced, well-documented case study that serves both as a historical record and as a learning resource for urban development practitioners, policymakers, and researchers.
"""

In [10]:
df

,Origin,Place,Type,Source,Source_Title,Similar_use_cases
0,ZP_UCS--DUB-D-UC1,Dublin,UC,# Use case : DUB-D-UC1\n\n\nCity: Dublin\n\n##...,Dublin energy monitoring and management.,## 1. Living Lab BIPV – Solar Building-Integra...
1,ZP_UCS--PTO-B-UC1,Porto,UC,# Use case : PTO-B-UC1\n\n\nCity: Porto\n\n## ...,Operational efficiency and sustainability impr...,Here are **five case studies** of products or ...
2,ZP_UCS--MDC-B-UC1,Madrid,UC,# Use case : MDC-B-UC1\n\n\nCity: Madrid\n\n##...,Electricity monitoring and sustainability repo...,Here are five detailed case studies of digital...
3,ZP_UCS--BRU-B-UC2,Brussels,UC,# Use case : BRU-B-UC2\n\n\nCity: Brussels\n\n...,Energy management platform for communities.,Here are five detailed European case studies i...
4,ZP_UCS--DUB-D-UC4,Dublin,UC,# Use case : DUB-D-UC4\n\n\nCity: Dublin\n\n##...,Remote control of energy systems.,## 1. SmartEnCity – Vitoria-Gasteiz Smart Dist...
5,ZP_UCS--DUB-D-UC3,Dublin,UC,# Use case : DUB-D-UC3\n\n\nCity: Dublin\n\n##...,Energy flow management for sustainability.,Here are five case studies of energy flow moni...
6,ZP_UCS--MGP-C-UC1,Madrid,UC,# Use case : MGP-C-UC1\n\n\nCity: Madrid\n\n##...,KPI visualization and reporting tool.,Here are five detailed case studies of **green...
7,ZP_UCS--AAR-A-UC3,Aarhus,UC,# Use case : AAR-A-UC3\n\n\nCity: Aarhus\n\n##...,Human-centered building design feedback tool.,## 1. Green Hub House\n\n* **Case study Title:...
8,ZP_UCS--BRU-C-UC1,Brussels,UC,# Use case : BRU-C-UC1\n\n\nCity: Brussels\n\n...,Optimizing Brussels mobility for sustainability.,## 1. eHUBS – Smart Shared Green Mobility Hubs...
9,ZP_UCS--MDC-C-UC1,Madrid,UC,# Use case : MDC-C-UC1\n\n\nCity: Madrid\n\n##...,Energy consumption monitoring in Madrid.,## 1. Cleanwatts Living Lab – AI-Powered Renew...
10,ZP_UCS--BRU-A-UC2,Brussels,UC,# Use case : BRU-A-UC2\n\n\nCity: Brussels\n\n...,Electricity monitoring for sustainable efficie...,Here are five detailed case studies of **digit...
11,ZP_UCS--AAR-A-UC4,Aarhus,UC,# Use case : AAR-A-UC4\n\n\nCity: Aarhus\n\n##...,Automated design assessments for sustainability.,## 1. CO-SHAPE Pilot: Circular Energy Park & C...
12,ZP_UCS--DUB-C-UC3,Dublin,UC,# Use case : DUB-C-UC3\n\n\nCity: Dublin\n\n##...,Incident reporting and tracking system.,## 1. Vienna Smart City – Seestadt Aspern\n\n*...
13,ZP_UCS--MDC-A-UC1,Madrid,UC,# Use case : MDC-A-UC1\n\n\nCity: Madrid\n\n##...,Electricity monitoring for sustainable managem...,## 1. Casa Sophia – Spain’s Most Eco-Friendly ...
14,ZP_UCS--PRG-A-UC3,Prague,UC,# Use case : PRG-A-UC3\n\n\nCity: Prague\n\n##...,Monitoring indoor climate and air quality.,1. **Smart Climate Control and Air Quality Mon...
15,ZP_UCS--MDC-D-UC1,Madrid,UC,# Use case : MDC-D-UC1\n\n\nCity: Madrid\n\n##...,Energy monitoring in Madrid neighborhood.,## 1. Positive Energy Neighbourhoods in Tartu\...
16,ZP_UCS--DUB-A-UC3,Dublin,UC,# Use case : DUB-A-UC3\n\n\nCity: Dublin\n\n##...,HVAC performance monitoring in Dublin.,## 1. Dublin Boiler House Sustainability Educa...
17,ZP_UCS--DUB-B-UC3,Dublin,UC,# Use case : DUB-B-UC3\n\n\nCity: Dublin\n\n##...,Monitoring energy flow for EVs.,Here are five detailed European case studies o...
18,ZP_UCS--MGP-A-UC1,Madrid,UC,# Use case : MGP-A-UC1\n\n\nCity: Madrid\n\n##...,Thermal demand forecasting tool.,X. Triple Eco-Carbon Neutral Co-Working Space\...
19,ZP_UCS--MGP-B-UC3,Madrid,UC,# Use case : MGP-B-UC3\n\n\nCity: Madrid\n\n##...,Optimizing Madrid's District Heating System.,Here are five case studies of district heating...
20,ZP_UCS--PRG-A-UC4,Prague,UC,# Use case : PRG-A-UC4\n\n\nCity: Prague\n\n##...,Performance monitoring for Green Building.,Here are five detailed case studies of smart a...
21,ZP_UCS--AAR-A-UC2,Aarhus,UC,# Use case : AAR-A-UC2\n\n\nCity: Aarhus\n\n##...,Human-centered design feedback tool.,## 1. Circle House: Denmark’s First Circular S...
22,ZP_UCS--BRU-B-UC1,Brussels,UC,# Use case : BRU-B-UC1\n\n\nCity: Brussels\n\n...,Information platform for energy communities.,Here are five detailed case studies of **energ...
23,ZP_UCS--PRG-A-UC1,Prague,UC,# Use case : PRG-A-UC1\n\n\nCity: Prague\n\n##...,Electricity monitoring for sustainable managem...,Here are five detailed case studies of **energ...
24,ZP_UCS--MGP-C-UC3,Madrid,UC,# Use case : MGP-C-UC3\n\n\nCity: Madrid\n\n##...,Energy monitoring for electric vehicles.,## 1. Stockholm: Clean Vehicles in Stockholm\n...
25,ZP_UCS--DUB-C-UC4,Dublin,UC,# Use case : DUB-C-UC4\n\n\nCity: Dublin\n\n##...,Incident management for Dublin Living Lab.,## 1. Green-Campus Living Lab (TU Dublin)\n\n*...
26,ZP_UCS--BRU-B-UC3,Brussels,UC,# Use case : BRU-B-UC3\n\n\nCity: Brussels\n\n...,Energy management and community engagement.,## 1. Savonnerie Heymans: A Former Soap Factor...
27,ZP_UCS--DUB-C-UC5,Dublin,UC,# Use case : DUB-C-UC5\n\n\nCity: Dublin\n\n##...,Dublin environment quality monitoring tool.,## 1. I-CHANGE Living Lab: Milan\n\n* **Case s...
28,ZP_UCS--PTO-B-UC2,Porto,UC,# Use case : PTO-B-UC2\n\n\nCity: Porto\n\n## ...,Energy optimization and performance improvement.,Here are five detailed case studies from Europ...
29,ZP_UCS--DUB-C-UC2,Dublin,UC,# Use case : DUB-C-UC2\n\n\nCity: Dublin\n\n##...,Dublin occupancy monitoring and optimization.,Here are five detailed case studies of occupan...
30,ZP_UCS--BRU-A-UC1,Brussels,UC,# Use case : BRU-A-UC1\n\n\nCity: Brussels\n\n...,Digital twins optimize energy consumption.,Here are five detailed case studies of similar...
31,ZP_UCS--PTO-A-UC2,Porto,UC,# Use case : PTO-A-UC2\n\n\nCity: Porto\n\n## ...,Energy optimization tool for campus.,Here are five case studies of sustainable urba...
32,ZP_UCS--DUB-A-UC4,Dublin,UC,# Use case : DUB-A-UC4\n\n\nCity: Dublin\n\n##...,Waste management optimization in Dublin.,## 1. Smart Waste Management Pilot in Helsinki...
33,ZP_UCS--DUB-A-UC1,Dublin,UC,# Use case : DUB-A-UC1\n\n\nCity: Dublin\n\n##...,Environmental monitoring for sustainable build...,## 1. Urban Sense: Real-Time Greenhouse Gas Em...
34,ZP_UCS--BRU-A-UC3,Brussels,UC,# Use case : BRU-A-UC3\n\n\nCity: Brussels\n\n...,Building climate monitoring and optimization.,## 1. Tivoli GreenCity: The First Sustainable ...
35,ZP_UCS--MGP-C-UC2,Madrid,UC,# Use case : MGP-C-UC2\n\n\nCity: Madrid\n\n##...,Madrid charging station monitoring system.,Here are five detailed case studies from Europ...
36,ZP_UCS--MGP-B-UC2,Madrid,UC,# Use case : MGP-B-UC2\n\n\nCity: Madrid\n\n##...,KPI optimization for efficient management.,Here are five case studies from European citie...
37,ZP_UCS--AAR-A-UC1,Aarhus,UC,# Use case : AAR-A-UC1\n\n\nCity: Aarhus\n\n##...,Rapid feedback for sustainable design.,Here are **five detailed case studies** from E...
38,ZP_UCS--AAR-B-UC1,Aarhus,UC,# Use case : AAR-B-UC1\n\n\nCity: Aarhus\n\n##...,Optimizing building performance and experience.,## 1. READY Project Demo Site – Aarhus\n\n* **...
39,ZP_UCS--DUB-A-UC2,Dublin,UC,# Use case : DUB-A-UC2\n\n\nCity: Dublin\n\n##...,Dublin's indoor environmental monitoring system.,## 1. Smart Readiness Indicator (SRI) Pilot – ...
40,ZP_UCS--BRU-B-UC4,Brussels,UC,# Use case : BRU-B-UC4\n\n\nCity: Brussels\n\n...,Interconnected Digital Twins for sustainability.,Here are five similar case studies from Europe...
41,ZP_UCS--PTO-A-UC1,Porto,UC,# Use case : PTO-A-UC1\n\n\nCity: Porto\n\n## ...,Energy awareness and consumption optimization.,Here are five case studies of **green building...
42,ZP_UCS--DUB-D-UC2,Dublin,UC,# Use case : DUB-D-UC2\n\n\nCity: Dublin\n\n##...,Energy consumption tracking and optimization.,Here are five detailed case studies of energy ...
43,ZP_UCS--PRG-A-UC2,Prague,UC,# Use case : PRG-A-UC2\n\n\nCity: Prague\n\n##...,Electricity monitoring in Prague neighborhood.,### 1. Smart Energy Monitoring in Amsterdam’s ...
44,ZP_UCS--MGP-B-UC1,Madrid,UC,# Use case : MGP-B-UC1\n\n\nCity: Madrid\n\n##...,Key performance indicators for energy efficiency.,Here are **five case studies** of district hea...
45,ZP_UCS--PTO-C-UC1,Porto,UC,# Use case : PTO-C-UC1\n\n\nCity: Porto\n\n## ...,Simulate and optimize energy systems.,Here are five detailed European case studies o...
46,ZP_UCS--DUB-B-UC1,Dublin,UC,# Use case : DUB-B-UC1\n\n\nCity: Dublin\n\n##...,Dublin car park management optimization.,Here are five detailed case studies from Europ...
47,ZP_UCS--DUB-B-UC2,Dublin,UC,# Use case : DUB-B-UC2\n\n\nCity: Dublin\n\n##...,Monitoring electric vehicle charging stations.,## 1. Cleanwatts Living Lab: AI-powered Renewa...
48,ZP_UCS--DUB-C-UC1,Dublin,UC,# Use case : DUB-C-UC1\n\n\nCity: Dublin\n\n##...,Optimize canteen food use sustainably.,## 1. Food Use Optimization in School Canteens...

In [11]:
newucs = []
responses = []
for ix, row in df.iterrows():
    nn = 0
    try:
        txt = row["Similar_use_cases"]
        if txt.startswith("\n## "):
            UCS = txt.split("\n## ")
        else:
            UCS = txt.split("\n## ")
        if len(UCS[0]) < 500:
            UCS = UCS[1:]
        for uc in UCS:
            nn += 1
            #n = uc.replace("#","").strip().split(" ")[0].strip(".")
            print(nn, row["Origin"])
            prompt = prompt_detail_template.format(case_study=uc)
            response = askp(prompt, size="high")
            responses.append(response)
            newucs.append({
                "Origin": row["Origin"],
                "Place": row["Place"],
                "Type": row["Type"],
                "Source": row["Source"],
                "Similar_use_cases": txt,
                "Similar_use_case_number": nn,
                "Similar_use_case_detail": response
            })
            print(response[:100])
            
        print("OK")
    except:
        print("error")
        pass

1 ZP_UCS--DUB-D-UC1
# Living Lab BIPV (Building-Integrated Photovoltaics)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFI
2 ZP_UCS--DUB-D-UC1
# Ethos Engineering Living Lab Digital Twin

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### *
3 ZP_UCS--DUB-D-UC1
# Integrated Energy Lab (IE Lab), UCD Energy Institute

---

## **I. INITIATIVE OVERVIEW AND IDENTIF
4 ZP_UCS--DUB-D-UC1
# Energy Living Lab (Provincia di Sassari, Italy)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATI
5 ZP_UCS--DUB-D-UC1
# Virtual Heating Plant Gleisdorf

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basi
OK
1 ZP_UCS--PTO-B-UC1
# Agra do Amial Renewable Energy Community

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

#
2 ZP_UCS--PTO-B-UC1
# FUN Porto (Urban Forest and BioSpots Network)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
3 ZP_UCS--PTO-B-UC1
# LIFE-myBUILDINGisGREEN: Falcão Primary School Green Roof Demonstration

## **I. INITIATIVE OVERVIE
4 ZP_UCS--PTO-B-UC1
# Porto di Mare Eco-District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Informat
5 ZP_UCS--PTO-B-UC1
# Sponge Parks and Social Housing Energy Communities (EXHAUSTION Horizon Project)

## **I. INITIATIV
OK
1 ZP_UCS--MDC-B-UC1
# Casa Sophia – Positive Energy Smart Home

## I. INITIATIVE OVERVIEW AND IDENTIFICATION

### Basic
2 ZP_UCS--MDC-B-UC1
# Orcasitas Community Energy Renovation

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
3 ZP_UCS--MDC-B-UC1
# HABITA-RES Urban Neighborhood Energy Visualization Tool

## **I. INITIATIVE OVERVIEW AND IDENTIFIC
4 ZP_UCS--MDC-B-UC1
# mySMARTLife – Smart City Lighthouse Project

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
5 ZP_UCS--MDC-B-UC1
# Sharing Cities – Smart District Demonstration (Milan)

---

## **I. INITIATIVE OVERVIEW AND IDENTI
OK
1 ZP_UCS--BRU-B-UC2
# Tivoli GreenCity – The First Sustainable Neighbourhood in Brussels

## **I. INITIATIVE OVERVIEW AN
2 ZP_UCS--BRU-B-UC2
# GreenBizz Energy Community

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Informat
3 ZP_UCS--BRU-B-UC2
# Be.SHARE – Brussels Sustainable Heating and Renewable Energy Community

## **I. INITIATIVE OVERVIE
4 ZP_UCS--BRU-B-UC2
# RESPONSE – integRatEd Solutions for POsitive eNergy and reSilient CitiEs

## **I. INITIATIVE OVERV
5 ZP_UCS--BRU-B-UC2
# Sharing Cities – Smart Urban Energy Platform

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

##
OK
1 ZP_UCS--DUB-D-UC4
# SmartEnCity – Vitoria-Gasteiz Smart District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

##
2 ZP_UCS--DUB-D-UC4
# Dockline A3 BER Retrofit

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Infor
3 ZP_UCS--DUB-D-UC4
# EnergyVille Smart Building Living Lab

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
4 ZP_UCS--DUB-D-UC4
# mySMARTLife Urban Digital Platform

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
5 ZP_UCS--DUB-D-UC4
# IRIS Smart Cities – Positive Energy Districts

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
OK
1 ZP_UCS--DUB-D-UC3
# Amsterdam Smart Energy Grid

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Informa
2 ZP_UCS--DUB-D-UC3
# Aspern Smart City Research (ASCR)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic I
3 ZP_UCS--DUB-D-UC3
# Lyon Confluence Smart Community

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Inf
4 ZP_UCS--DUB-D-UC3
# REMOURBAN – Nottingham Lighthouse District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
5 ZP_UCS--DUB-D-UC3
# mySMARTLife – Hamburg Smart District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basi
OK
1 ZP_UCS--MGP-C-UC1
# Madrid Nuevo Norte Urban Regeneration

## I. INITIATIVE OVERVIEW AND IDENTIFICATION

### Basic Inf
2 ZP_UCS--MGP-C-UC1
# Orcasitas Community Energy-Efficient Renovation

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

3 ZP_UCS--MGP-C-UC1
# Lyon Confluence Smart District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Info
4 ZP_UCS--MGP-C-UC1
# Aspern Smart City Demonstration (Smarter Together)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
5 ZP_UCS--MGP-C-UC1
# Milan Porta Romana Sharing Cities (Horizon 2020: Sharing Cities)

## **I. INITIATIVE OVERVIEW AND
OK
1 ZP_UCS--AAR-A-UC3
# Green Hub House

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information**
- **I
2 ZP_UCS--AAR-A-UC3
# Lisbjerg Sustainable Neighborhood

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic I
3 ZP_UCS--AAR-A-UC3
# Spørring Circular Energy Park (CO-SHAPE Project)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**
4 ZP_UCS--AAR-A-UC3
# Madrid Nuevo Norte Green District (PROBONO Project Living Lab)

## **I. INITIATIVE OVERVIEW AND ID
5 ZP_UCS--AAR-A-UC3
# Dublin Green Building Neighbourhood (PROBONO Project)

---

## **I. INITIATIVE OVERVIEW AND IDENTI
OK
1 ZP_UCS--BRU-C-UC1
# eHUBS – Smart Shared Green Mobility Hubs

## I. INITIATIVE OVERVIEW AND IDENTIFICATION

### Basic
2 ZP_UCS--BRU-C-UC1
# Tivoli GreenCity Sustainable Neighbourhood

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
3 ZP_UCS--BRU-C-UC1
# Green Corridor Project

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information*
4 ZP_UCS--BRU-C-UC1
# 10-Minute City Urban Planning Tool

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
5 ZP_UCS--BRU-C-UC1
# Buildings as Material Banks (BAMB) – Circular Economy for Urban Development

## **I. INITIATIVE OV
OK
1 ZP_UCS--MDC-C-UC1
# Cleanwatts Living Lab – AI-Powered Renewable Energy Community

---

## **I. INITIATIVE OVERVIEW AN
2 ZP_UCS--MDC-C-UC1
# Energy Systems Catapult Living Lab

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **B
3 ZP_UCS--MDC-C-UC1
# Living Lab for Testing Digital Energy Solutions at JRC Ispra

## **I. INITIATIVE OVERVIEW AND IDEN
4 ZP_UCS--MDC-C-UC1
# EU-DREAM: Effective Uptake of Digital Services to Repower European Consumers and Communities as Ac
5 ZP_UCS--MDC-C-UC1
# i-STENTORE Living Lab for Smart Energy Storage Deployment (Horizon Europe Project)

## **I. INITIA
OK
1 ZP_UCS--BRU-A-UC2
# Tivoli GreenCity – The First Sustainable Neighbourhood in Brussels

## **I. INITIATIVE OVERVIEW AN
2 ZP_UCS--BRU-A-UC2
# Living Labs Brussels Retrofit Project

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
3 ZP_UCS--BRU-A-UC2
# Waterschei Positive Energy Neighbourhood (oPEN Lab)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFI
4 ZP_UCS--BRU-A-UC2
# RESPONSE (integRatEd Solutions for POsitive eNergy and reSilient CitiEs)

## **I. INITIATIVE OVERV
5 ZP_UCS--BRU-A-UC2
# oPEN Lab Positive Energy Neighbourhoods

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **B
OK
1 ZP_UCS--AAR-A-UC4
# CO-SHAPE Circular Energy Park & Governance Innovation

## **I. INITIATIVE OVERVIEW AND IDENTIFICAT
2 ZP_UCS--AAR-A-UC4
# READY Project: Integrated Energy Retrofitting Demonstrator (READY Site Aarhus – Integrated Smart C
3 ZP_UCS--AAR-A-UC4
# Green Hub House – Experimental Urban and Climate-Friendly Community

## **I. INITIATIVE OVERVIEW A
4 ZP_UCS--AAR-A-UC4
# oPEN Lab – Positive Energy Neighbourhoods in Tartu, Pamplona, and Genk

## **I. INITIATIVE OVERVIE
5 ZP_UCS--AAR-A-UC4
# ARV – Climate Positive Circular Communities

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**
OK
1 ZP_UCS--DUB-C-UC3
```
# Seestadt Aspern

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information**
-
2 ZP_UCS--DUB-C-UC3
# Cherrywood Urban Development – Barrington Building & TC1

## **I. INITIATIVE OVERVIEW AND IDENTIFI
3 ZP_UCS--DUB-C-UC3
# Mapping Green Dublin – Community Engagement for Urban Trees

---

## **I. INITIATIVE OVERVIEW AND
4 ZP_UCS--DUB-C-UC3
# IGBC Biodiversity Case Study – National Forensic Mental Health Service (NFMHS) Project

---

## **
5 ZP_UCS--DUB-C-UC3
# mySMARTLife – Urban Data-Driven Sustainability Platform (Nantes, France)

---

## **I. INITIATIVE
OK
1 ZP_UCS--MDC-A-UC1
# Casa Sophia: Automating Spain’s Most Eco-Friendly Home

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
2 ZP_UCS--MDC-A-UC1
# HABITA-RES: Energy Assessment and Refurbishment of Vulnerable Urban Areas

## **I. INITIATIVE OVER
3 ZP_UCS--MDC-A-UC1
# Energy-Efficient Renovation in Orcasitas with EPS Insulation

## I. INITIATIVE OVERVIEW AND IDENTI
4 ZP_UCS--MDC-A-UC1
# Staying Green: Madrid’s Urban Green Space Monitoring

---

## **I. INITIATIVE OVERVIEW AND IDENTIF
5 ZP_UCS--MDC-A-UC1
# Ampeers Energy Digital Twin for Districts (SMARTER TOGETHER Project)

## **I. INITIATIVE OVERVIEW
6 ZP_UCS--MDC-A-UC1
# CityLoops – Circular Construction and Demolition Waste Management

## **I. INITIATIVE OVERVIEW AND
OK
1 ZP_UCS--PRG-A-UC3
# EDGE Olympic – Smart Climate Control and Air Quality Monitoring

---

## **I. INITIATIVE OVERVIEW
OK
1 ZP_UCS--MDC-D-UC1
# oPEN Lab – Positive Energy Neighbourhoods in Tartu

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
2 ZP_UCS--MDC-D-UC1
# UNCHAIN Project – Sustainable Urban Logistics and Low Emission Zones

## **I. INITIATIVE OVERVIEW
3 ZP_UCS--MDC-D-UC1
# ARV Project – Climate Positive Circular Communities

## **I. INITIATIVE OVERVIEW AND IDENTIFICATIO
4 ZP_UCS--MDC-D-UC1
# Smarter Together – Sustainable Urban Districts (Lyon)

## **I. INITIATIVE OVERVIEW AND IDENTIFICAT
5 ZP_UCS--MDC-D-UC1
# mySMARTLife – Positive Energy Block Demonstration

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
OK
1 ZP_UCS--DUB-A-UC3
# Rediscovery Centre Ballymun (Dublin Boiler House Sustainability Education Centre)

---

## **I. IN
2 ZP_UCS--DUB-A-UC3
# Ella House High-Efficiency HVAC Retrofit

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **
3 ZP_UCS--DUB-A-UC3
# Tallaght District Heating Using Data Center Waste Heat

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
4 ZP_UCS--DUB-A-UC3
# Dublin Docklands Green Heating Network

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
5 ZP_UCS--DUB-A-UC3
# SmartEnCity – Vitoria-Gasteiz Green Neighborhood Retrofit

## **I. INITIATIVE OVERVIEW AND IDENTIF
6 ZP_UCS--DUB-A-UC3
# mySMARTLife Project – Nantes

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Inform
OK
1 ZP_UCS--DUB-B-UC3
# Flexible Smart Charging for EVs (Amsterdam Smart Charging Pilot)

## **I. INITIATIVE OVERVIEW AND
2 ZP_UCS--DUB-B-UC3
# Seestadt Aspern Smart City District

---

## I. INITIATIVE OVERVIEW AND IDENTIFICATION

### Basic
3 ZP_UCS--DUB-B-UC3
# EnergyLab Nordhavn (Nordhavn Smart Energy Living Lab)

---

## **I. INITIATIVE OVERVIEW AND IDENTI
4 ZP_UCS--DUB-B-UC3
# SPARCS Espoo Positive Energy District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
5 ZP_UCS--DUB-B-UC3
# RESPONSE Dijon – Positive Energy Block

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
OK
1 ZP_UCS--MGP-A-UC1
# Triple – Eco-Carbon Neutral Co-Working and Event Space

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
OK
1 ZP_UCS--MGP-B-UC3
# Madrid Nuevo Norte Urban Geothermal Power Network

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION*
2 ZP_UCS--MGP-B-UC3
# Móstoles Biomass District Heating Network

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### *
3 ZP_UCS--MGP-B-UC3
# Manchester Civic Quarter Heat Network (CQHN)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

##
4 ZP_UCS--MGP-B-UC3
# UCM Complutense University District Heating Network Renovation

---

## **I. INITIATIVE OVERVIEW A
5 ZP_UCS--MGP-B-UC3
# THERMOS Project: District Heating & Cooling Planning Tools (Horizon 2020)

## **I. INITIATIVE OVER
6 ZP_UCS--MGP-B-UC3
# 3G to 5G District Heating and Cooling Networks (Horizon Europe)

---

## **I. INITIATIVE OVERVIEW
OK
1 ZP_UCS--PRG-A-UC4
# Modřanský cukrovar Blue-Green District

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Ba
2 ZP_UCS--PRG-A-UC4
# Smíchov City – Comprehensive Urban Brownfield Redevelopment

## **I. INITIATIVE OVERVIEW AND IDENT
3 ZP_UCS--PRG-A-UC4
# City Green Court

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information**
- **
4 ZP_UCS--PRG-A-UC4
# Smart Kalasatama – Helsinki’s Digital and Sustainable District

## **I. INITIATIVE OVERVIEW AND ID
5 ZP_UCS--PRG-A-UC4
# SmartEnCity – Lighthouse District Smart Renovation (Vitoria-Gasteiz, Spain)

## **I. INITIATIVE OV
OK
1 ZP_UCS--AAR-A-UC2
# Circle House – Denmark’s First Circular Social Housing Project

## **I. INITIATIVE OVERVIEW AND ID
2 ZP_UCS--AAR-A-UC2
# Lisbjerg Sustainable Housing Development

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **
3 ZP_UCS--AAR-A-UC2
# BIPED – Building Intelligent Positive Energy Districts

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
4 ZP_UCS--AAR-A-UC2
# The Dome – Green Community House (Domen)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

#
5 ZP_UCS--AAR-A-UC2
# CO-SHAPE: Co-Shaping Areas in Peri-Urban Environments

## **I. INITIATIVE OVERVIEW AND IDENTIFICAT
OK
1 ZP_UCS--BRU-B-UC1
# Smart Kalasatama – Digital Energy Community Platform

## I. INITIATIVE OVERVIEW AND IDENTIFICATION
2 ZP_UCS--BRU-B-UC1
# Energent Energy Community Platform (Freiburg)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
3 ZP_UCS--BRU-B-UC1
# Sharing Cities – Digital Energy Platform

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **
4 ZP_UCS--BRU-B-UC1
# ATELIER: AmsTErdam and BiLbao cItizen drivEn smaRt cities

## **I. INITIATIVE OVERVIEW AND IDENTIF
5 ZP_UCS--BRU-B-UC1
# POCITYF – Positive Energy Blocks Digital Platform

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION*
OK
1 ZP_UCS--PRG-A-UC1
# Residential Building in Prague Monitors Energy Consumption via M-Bus

## **I. INITIATIVE OVERVIEW
2 ZP_UCS--PRG-A-UC1
# Prague Renewable Energy Community and Green Building Renovation

---

## **I. INITIATIVE OVERVIEW
3 ZP_UCS--PRG-A-UC1
# Energy Consumption Measurement Digitization – Smart Prague Initiative

## **I. INITIATIVE OVERVIEW
4 ZP_UCS--PRG-A-UC1
# ASCEND Smart Energy Neighborhood Demonstration

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATIO
5 ZP_UCS--PRG-A-UC1
# Enectiva: Cloud-Based Energy Monitoring for Green Buildings

## **I. INITIATIVE OVERVIEW AND IDENT
OK
1 ZP_UCS--MGP-C-UC3
# Stockholm's Clean Vehicles Initiative

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
2 ZP_UCS--MGP-C-UC3
# Smarter Together – Smart Mobility Solutions

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
3 ZP_UCS--MGP-C-UC3
# CIVITAS ECCENTRIC – Electric Vehicle Monitoring and Optimization

## **I. INITIATIVE OVERVIEW AND
4 ZP_UCS--MGP-C-UC3
# GreenCharge – Incentivising Sustainable Urban Mobility

## **I. INITIATIVE OVERVIEW AND IDENTIFICA
5 ZP_UCS--MGP-C-UC3
# eHUBS – Smart Shared Mobility Hubs

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
OK
1 ZP_UCS--DUB-C-UC4
```
# Green-Campus Living Lab (TU Dublin)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **B
2 ZP_UCS--DUB-C-UC4
# Aarhus Smart Building Elevator Usage Analytics

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**


3 ZP_UCS--DUB-C-UC4
# Brussels Green Building District Monitoring

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
4 ZP_UCS--DUB-C-UC4
```
# Madrid Connected Green Neighbourhood Demonstrator (PROBONO Horizon Project)

## **I. INITIATIV
5 ZP_UCS--DUB-C-UC4
# Porto Sustainable Neighbourhood Living Lab (PROBONO Horizon Project)

## **I. INITIATIVE OVERVIEW
OK
1 ZP_UCS--BRU-B-UC3
# Savonnerie Heymans: A Former Soap Factory Turned Into a Sustainable Housing Project

---

## **I.
2 ZP_UCS--BRU-B-UC3
# Tivoli GreenCity

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Information**

- *
3 ZP_UCS--BRU-B-UC3
# GreenBizz Energy Community

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Inf
4 ZP_UCS--BRU-B-UC3
# RESPONSE Project – Positive Energy Neighbourhoods

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION*
5 ZP_UCS--BRU-B-UC3
# Buildings as Material Banks (BAMB)

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **B
OK
1 ZP_UCS--DUB-C-UC5
# I-CHANGE Milan Living Lab

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Informati
2 ZP_UCS--DUB-C-UC5
# Trinity College Dublin Living Lab – Air Quality Monitoring

## **I. INITIATIVE OVERVIEW AND IDENTI
3 ZP_UCS--DUB-C-UC5
# SCORE Coastal City Living Lab – Rotterdam

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### *
4 ZP_UCS--DUB-C-UC5
```
# Urban GreenUP – Nature-Based Solutions for Urban Resilience

## **I. INITIATIVE OVERVIEW AND I
5 ZP_UCS--DUB-C-UC5
# mySMARTLife: Urban Data Platform for Smart City Management

## **I. INITIATIVE OVERVIEW AND IDENTI
OK
1 ZP_UCS--PTO-B-UC2
# Agra do Amial Renewable Energy Community

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

#
2 ZP_UCS--PTO-B-UC2
# FUN Porto – Urban Native Forest Initiative

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

###
3 ZP_UCS--PTO-B-UC2
```
# LIFE-myBUILDINGisGREEN: Green Roof Retrofit at Falcão Primary School

## **I. INITIATIVE OVERV
4 ZP_UCS--PTO-B-UC2
# The Fifth Façade Project – Praça de Lisboa Olive Grove Green Roof

## I. INITIATIVE OVERVIEW AND I
5 ZP_UCS--PTO-B-UC2
# Social Green – Green Renovation for Social Housing (Interreg Europe)

---

## **I. INITIATIVE OVER
OK
1 ZP_UCS--DUB-C-UC2
# People-Counting Sensors: Enhancing Building Efficiency with GDPR Compliance at TU Dublin

## **I.
2 ZP_UCS--DUB-C-UC2
# Ethos Engineering Living Lab

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic Inform
3 ZP_UCS--DUB-C-UC2
# Hub Criativo do Beato Living Lab

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic In
4 ZP_UCS--DUB-C-UC2
# The Edge Amsterdam: BREEAM-NL Smart Building Pilot

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION
5 ZP_UCS--DUB-C-UC2
```
# Syn.ikia: Plus-Energy Neighbourhood Demonstrator

## **I. INITIATIVE OVERVIEW AND IDENTIFICATI
OK
1 ZP_UCS--BRU-A-UC1
# Tivoli GreenCity Sustainable Neighbourhood

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

2 ZP_UCS--BRU-A-UC1
# Buildings As Material Banks (BAMB)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
3 ZP_UCS--BRU-A-UC1
# Bridge City – Regenerative Development

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Ba
4 ZP_UCS--BRU-A-UC1
# Transforming Collectivity – Community Housing for Socially Empowered Living

## **I. INITIATIVE OV
5 ZP_UCS--BRU-A-UC1
# Oxygen Office Building – BAMB Pilot (Horizon 2020 Project)

---

## **I. INITIATIVE OVERVIEW AND I
OK
1 ZP_UCS--PTO-A-UC2
# Agra do Amial Renewable Energy Community

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **
2 ZP_UCS--PTO-A-UC2
# FUN Porto Urban Forest & BioSpots Network

---

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**


3 ZP_UCS--PTO-A-UC2
# LIFE-myBUILDINGisGREEN Project: Falcão Primary School

## **I. INITIATIVE OVERVIEW AND IDENTIFICAT
4 ZP_UCS--PTO-A-UC2
# Amsterdam Zuidoost Energy Community (ATELIER Project)

## I. INITIATIVE OVERVIEW AND IDENTIFICATIO
5 ZP_UCS--PTO-A-UC2
# La Pinada Eco-Neighbourhood (MAKING-CITY)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### *
OK
1 ZP_UCS--DUB-A-UC4
# Smart Waste Management Pilot – Jätkäsaari District, Helsinki

## **I. INITIATIVE OVERVIEW AND IDEN
2 ZP_UCS--DUB-A-UC4
# Barcelona Smart Waste City Project

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
3 ZP_UCS--DUB-A-UC4
# Milan Door-to-Door Food Waste Collection Program

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**
4 ZP_UCS--DUB-A-UC4
# Circular South (Horizon 2020 Project)

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Bas
5 ZP_UCS--DUB-A-UC4
# SmartWaste – Smart Waste Management in Stavanger (Horizon 2020 Project)

---

## **I. INITIATIVE O
OK
1 ZP_UCS--DUB-A-UC1
# Urban Sense: Monitoring Greenhouse Gas Emissions in Real Time Across Dublin

## **I. INITIATIVE OV
2 ZP_UCS--DUB-A-UC1
# Public Building Energy Monitoring at Wood Quay Civic Offices

## **I. INITIATIVE OVERVIEW AND IDEN
3 ZP_UCS--DUB-A-UC1
# Dublin City Air and Noise Monitoring Initiative

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

4 ZP_UCS--DUB-A-UC1
# Smart Green Roof Monitoring Project

## **I. INITIATIVE OVERVIEW AND IDENTIFICATION**

### **Basic
5 ZP_UCS--DUB-A-UC1
# IRIS Smart Cities – Utrecht Lighthouse Demonstration


In [12]:
d = pd.DataFrame(newucs)[["Origin","Similar_use_case_number","Similar_use_case_detail"]]
d[87:90]

,Origin,Similar_use_case_number,Similar_use_case_detail
87,ZP_UCS--DUB-B-UC3,5,# RESPONSE Dijon – Positive Energy Block\n\n--...
88,ZP_UCS--MGP-A-UC1,1,# Triple – Eco-Carbon Neutral Co-Working and E...
89,ZP_UCS--MGP-B-UC3,1,# Madrid Nuevo Norte Urban Geothermal Power Ne...

# Scoring

In [13]:
len(responses)

238

In [14]:
analyses = []
for response in responses:
    print(response[:20])
    analysis = brain.analyseText( txt=response,
            TypeOfItem = "Activity",
            Source="open_web_review",
            Place="TBC",
            MIN=7,
            Reviewed=False,
            MODEL="gpt-4o-mini")
    analyses.append(analysis)
analyses = pd.concat(analyses)

# Living Lab BIPV (B
Already done
# Ethos Engineering
Already done
# Integrated Energy
Already done
# Energy Living Lab
Already done
# Virtual Heating Pl
Already done
# Agra do Amial Rene
Already done
# FUN Porto (Urban F
Already done
# LIFE-myBUILDINGisG
Already done
# Porto di Mare Eco-
Already done
# Sponge Parks and S
Already done
# Casa Sophia – Posi
Already done
# Orcasitas Communit
Already done
# HABITA-RES Urban N
Already done
# mySMARTLife – Smar
Already done
# Sharing Cities – S
Already done
# Tivoli GreenCity –
Already done
# GreenBizz Energy C
Already done
# Be.SHARE – Brussel
Already done
# RESPONSE – integRa
Already done
# Sharing Cities – S
Already done
# SmartEnCity – Vito
Already done
# Dockline A3 BER Re
Already done
# EnergyVille Smart
Already done
# mySMARTLife Urban
Already done
# IRIS Smart Cities
Already done
# Amsterdam Smart En
Already done
# Aspern Smart City
Already done
# Lyon Confluence Sm
Already done
# REMOURBAN – Nottin
Already done
# mySMARTLife – Hamb
Already done
# Madrid Nuevo Norte
Already done
# Orcasitas Communit
Already done
# Lyon Confluence Sm
Already done
# Aspern Smart City
Already done
# Milan Porta Romana
Already done
# Green Hub House

#
Already done
# Lisbjerg Sustainab
Already done
# Spørring Circular
Already done
# Madrid Nuevo Norte
Already done
# Dublin Green Build
Already done
# eHUBS – Smart Shar
Already done
# Tivoli GreenCity S
Already done
# Green Corridor Pro
Already done
# 10-Minute City Urb
Already done
# Buildings as Mater
Already done
# Cleanwatts Living
Already done
# Energy Systems Cat
Already done
# Living Lab for Tes
Already done
# EU-DREAM: Effectiv
Already done
# i-STENTORE Living
Already done
# Tivoli GreenCity –
Already done
# Living Labs Brusse
Already done
# Waterschei Positiv
Already done
# RESPONSE (integRat
Already done
# oPEN Lab Positive
Already done
# CO-SHAPE Circular
Already done
# READY Project: Int
Already done
# Green Hub House –
Already done
# oPEN Lab – Positiv
Already done
# ARV – Climate Posi
Already done
```
# Seestadt Asper
Already done
# Cherrywood Urban D
Already done
# Mapping Green Dubl
Already done
# IGBC Biodiversity
Already done
# mySMARTLife – Urba
Already done
# Casa Sophia: Autom
Already done
# HABITA-RES: Energy
Already done
# Energy-Efficient R
Already done
# Staying Green: Mad
Already done
# Ampeers Energy Dig
Already done
# CityLoops – Circul
Already done
# EDGE Olympic – Sma
Already done
# oPEN Lab – Positiv
Already done
# UNCHAIN Project –
Already done
# ARV Project – Clim
Already done
# Smarter Together –
Already done
# mySMARTLife – Posi
Already done
# Rediscovery Centre
Already done
# Ella House High-Ef
Already done
# Tallaght District
Already done
# Dublin Docklands G
Already done
# SmartEnCity – Vito
Already done
# mySMARTLife Projec
Already done
# Flexible Smart Cha
Already done
# Seestadt Aspern Sm
Already done
# EnergyLab Nordhavn
Already done
# SPARCS Espoo Posit
Already done
# RESPONSE Dijon – P
Already done
# Triple – Eco-Carbo
Already done
# Madrid Nuevo Norte
Already done
# Móstoles Biomass D
Already done
# Manchester Civic Q
Already done
# UCM Complutense Un
Already done
# THERMOS Project: D
Already done
# 3G to 5G District
Already done
# Modřanský cukrovar
Already done
# Smíchov City – Com
Already done
# City Green Court


Already done
# Smart Kalasatama –
Already done
# SmartEnCity – Ligh
Already done
# Circle House – Den
Already done
# Lisbjerg Sustainab
Already done
# BIPED – Building I
Already done
# The Dome – Green C
Already done
# CO-SHAPE: Co-Shapi
Already done
# Smart Kalasatama –
Already done
# Energent Energy Co
Already done
# Sharing Cities – D
Already done
# ATELIER: AmsTErdam
Already done
# POCITYF – Positive
Already done
# Residential Buildi
Already done
# Prague Renewable E
Already done
# Energy Consumption
Already done
# ASCEND Smart Energ
Already done
# Enectiva: Cloud-Ba
Already done
# Stockholm's Clean
Already done
# Smarter Together –
Already done
# CIVITAS ECCENTRIC
Already done
# GreenCharge – Ince
Already done
# eHUBS – Smart Shar
Already done
```
# Green-Campus L
Already done
# Aarhus Smart Build
Already done
# Brussels Green Bui
Already done
```
# Madrid Connect
Already done
# Porto Sustainable
Already done
# Savonnerie Heymans
Already done
# Tivoli GreenCity


Already done
# GreenBizz Energy C
Already done
# RESPONSE Project –
Already done
# Buildings as Mater
Already done
# I-CHANGE Milan Liv
Already done
# Trinity College Du
Already done
# SCORE Coastal City
Already done
```
# Urban GreenUP
Already done
# mySMARTLife: Urban
Already done
# Agra do Amial Rene
Already done
# FUN Porto – Urban
Already done
```
# LIFE-myBUILDIN
Already done
# The Fifth Façade P
Already done
# Social Green – Gre
Already done
# People-Counting Se
Already done
# Ethos Engineering
Already done
# Hub Criativo do Be
Already done
# The Edge Amsterdam
Already done
```
# Syn.ikia: Plus
Already done
# Tivoli GreenCity S
Already done
# Buildings As Mater
Already done
# Bridge City – Rege
Already done
# Transforming Colle
Already done
# Oxygen Office Buil
Already done
# Agra do Amial Rene
Already done
# FUN Porto Urban Fo
Already done
# LIFE-myBUILDINGisG
Already done
# Amsterdam Zuidoost
Already done
# La Pinada Eco-Neig
Already done
# Smart Waste Manage
Already done
# Barcelona Smart Wa
Already done
# Milan Door-to-Door
Already done
# Circular South (Ho
Already done
# SmartWaste – Smart
Already done
# Urban Sense: Monit
Already done
# Public Building En
Already done
# Dublin City Air an
Already done
# Smart Green Roof M
Already done
# IRIS Smart Cities
Already done
# Sharing Cities – S
Already done
# Tivoli GreenCity –
Already done
# Smart Kalasatama D
Already done
# Aspern Smart City
Already done
# Amsterdam Smart En
Already done
# Lyon Confluence Sm
Already done
# Smart EV Charging
Already done
# Natural Wood in Af
Already done
# Madrid Nuevo Norte
Already done
# SRI4Cities – Smart
Already done
# Sharing Cities – I
Already done
# Manchester Civic Q
Already done
# Districlima: Barce
Already done
# Barrio La Pinada D
Already done
# FLEXYNETS – Intell
Already done
# 3G to 5G District
Already done
# TRÆ – Tall Timber
Already done
# Lisbjerg – Sustain
Already done
# AARhus by BIG – Gr
Already done
# Spørring Circular
Already done
# BIPED – Building I
Already done
# READY Project Demo
Already done
# Lisbjerg – Sustain
Already done
# CO-SHAPE – Peri-Ur
Already done
# Green Hub House –
Already done
# Sharing Cities – S
Already done
# IRIS Smart Cities
Already done
# Amsterdam Smart Bu
Already done
# Seestadt Aspern Sm
Already done
# Mapping Green Dubl
Already done
# SmartEnCity: Integ
Already done
# Sharing Cities: Sm
Already done
# Tivoli GreenCity –
Already done
# Buildings as Mater
Already done
# Bridge City – Rege
Already done
# Sharing Cities: In
Already done
# mySMARTLife – Inte
Already done
# Agra do Amial Rene
Already done
# LIFE-myBUILDINGisG
Already done
# Praça de Lisboa Gr
Already done
# Porto di Mare Eco-
Already done
# LIFE-myBUILDINGisG
Already done
# Cleanwatts Living
Already done
# Ethos Engineering
Already done
# Living Lab BIPV -
Already done
# DT-Enabled Residen
Already done
# SSE Airtricity Sma
Already done
# Smart Energy Manag
Already done
# Geothermal Distric
Already done
# Høje Taastrup 4th
Already done
# Barrio La Pinada D
Already done
# Heerlen Mijnwater
Already done
# Vitoria-Gasteiz DH
Already done
# Agra do Amial Rene
Already done
# Falcão Primary Sch
Already done
# Praça de Lisboa Ol
Already done
# Lyon Confluence Sm
Already done
# H22 – The Making o
Already done
# Zuidas Smart Mobil
Already done
# eParkomat EV and S
Already done
# Lyon Confluence Sm
Already done
# REMOURBAN: REgener
Already done
# Sharing Cities: Sm
Already done
# Cleanwatts Living
Already done
# Open Thor Living L
Already done
# IREN Living Lab: E
Already done
# Tallaght SmartGrid
Already done
# SSE Airtricity Liv
Already done
# Food Smart Schools
Already done
# Smart Waste Reduct
Already done
# Eco-Canteen Food W
Already done
# Green Canteen Digi
Already done
# Circular Canteen M
Already done

# Saving

In [15]:
d = d[["Origin","Similar_use_case_number","Similar_use_case_detail"]].drop_duplicates()
d.columns = ["ZP_UC","Similar_use_case_number","Similar_use_case_detail"]
d

,ZP_UC,Similar_use_case_number,Similar_use_case_detail
0,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...
1,ZP_UCS--DUB-D-UC1,2,# Ethos Engineering Living Lab Digital Twin\n\...
2,ZP_UCS--DUB-D-UC1,3,"# Integrated Energy Lab (IE Lab), UCD Energy I..."
3,ZP_UCS--DUB-D-UC1,4,"# Energy Living Lab (Provincia di Sassari, Ita..."
4,ZP_UCS--DUB-D-UC1,5,# Virtual Heating Plant Gleisdorf\n\n---\n\n##...
...,...,...,...
233,ZP_UCS--DUB-C-UC1,1,# Food Smart Schools Initiative\n\n## **I. INI...
234,ZP_UCS--DUB-C-UC1,2,# Smart Waste Reduction in Canteens (Gothenbur...
235,ZP_UCS--DUB-C-UC1,3,# Eco-Canteen Food Waste Management Initiative...
236,ZP_UCS--DUB-C-UC1,4,"# Green Canteen Digital Twin – Helsinki, Finla..."
237,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net..."

In [16]:
memory = analyses.merge(d, left_on=["Source"], right_on=["Similar_use_case_detail"])
memory["id"] = memory["ZP_UC"] + "_" + memory["Similar_use_case_number"].astype(str)
memory

,FromProbono,Origin,Place,Type,Source,Justification,Purpose,Issue,Scale,Score,Justification_Short,Source_Title,Reviewed,model,timestamp,reviewsrc,ZP_UC,Similar_use_case_number,Similar_use_case_detail,id
0,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The Living Lab BIPV represents a pioneering in...,Attractiveness,"Innovation, creativity and research",Building,5,Innovative building-integrated photovoltaics m...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
1,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The initiative focuses on reducing the environ...,Preservation and improvement of environment,Biodiversity and ecosystem services,Building,4,Sustainable buildings with renewable energy.,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
2,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,"By integrating renewable energy solutions, the...",Resilience,Health and care in the community,Neighbourhood,4,Renewable energy boosts community resilience.,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
3,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The Living Lab BIPV emphasizes efficient resou...,Responsible resource use,Economy and sustainable production and consump...,Building,5,Energy-generating building materials promote s...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
4,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,Though primarily focused on technological inno...,Social cohesion,"Living together, interdependence and mutuality",Neighbourhood,3,Living Lab promotes collaboration and sustaina...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2272,False,open_web_review,TBC,Activity,"# Circular Canteen Management – Amsterdam, Net...",By reducing food waste and improving the quali...,Well-being,Health and care in the community,Neighbourhood,4,Improving food quality enhances employee welln...,Circular canteen waste reduction initiative.,False,gpt-4o-mini,"11/22/2025, 12:07:55",N/A,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net...",ZP_UCS--DUB-C-UC1_5
2273,False,open_web_review,TBC,Activity,"# Circular Canteen Management – Amsterdam, Net...","The circular canteen initiative, by providing ...",Attractiveness,Mobility,Neighbourhood,3,Local food services enhance staff mobility.,Circular canteen waste reduction initiative.,False,gpt-4o-mini,"11/22/2025, 12:07:55",N/A,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net...",ZP_UCS--DUB-C-UC1_5
2274,False,open_web_review,TBC,Activity,"# Circular Canteen Management – Amsterdam, Net...","By focusing on local sourcing of food, the ini...",Preservation and improvement of environment,Biodiversity and ecosystem services,Neighbourhood,3,Supports biodiversity through local sourcing.,Circular canteen waste reduction initiative.,False,gpt-4o-mini,"11/22/2025, 12:07:55",N/A,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net...",ZP_UCS--DUB-C-UC1_5
2275,False,open_web_review,TBC,Activity,"# Circular Canteen Management – Amsterdam, Net...",The initiative emphasizes stakeholder engageme...,Resilience,"Governance, empowerment and engagement",Neighbourhood,4,Stakeholder engagement fosters community resil...,Circular canteen waste reduction initiative.,False,gpt-4o-mini,"11/22/2025, 12:07:55",N/A,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net...",ZP_UCS--DUB-C-UC1_5
2276,False,open_web_review,TBC,Activity,"# Circular Canteen Management – Amsterdam, Net...",Through the implementation of digital monitori...,Responsible resource use,Community smart infrastructures,Neighbourhood,3,Digital systems optimize canteen resource use.,Circular canteen waste reduction initiative.,False,gpt-4o-mini,"11/22/2025, 12:07:55",N/A,ZP_UCS--DUB-C-UC1,5,"# Circular Canteen Management – Amsterdam, Net...",ZP_UCS--DUB-C-UC1_5

In [17]:
memory.to_parquet("output/activities_open_web.parquet.gzip", compression="gzip")

# Create pages

In [6]:
import pandas as pd

In [7]:
memory = pd.read_parquet("output/activities_open_web.parquet.gzip")
memory.head(2)

,FromProbono,Origin,Place,Type,Source,Justification,Purpose,Issue,Scale,Score,Justification_Short,Source_Title,Reviewed,model,timestamp,reviewsrc,ZP_UC,Similar_use_case_number,Similar_use_case_detail,id
0,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The Living Lab BIPV represents a pioneering in...,Attractiveness,"Innovation, creativity and research",Building,5,Innovative building-integrated photovoltaics m...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1
1,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The initiative focuses on reducing the environ...,Preservation and improvement of environment,Biodiversity and ecosystem services,Building,4,Sustainable buildings with renewable energy.,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1

In [8]:
HEADER = """---
layout: default
title: "TITLE"
parent: PARENT
has_children: true
nav_order: NAVORDER
---\n\n"""

In [9]:

def convert_links_to_footnotes(text):
    """
    Convert (src: LINK ) patterns to markdown footnotes and add footnote list at the end.
    
    Args:
        text (str): Input text containing (src: LINK ) patterns
        
    Returns:
        str: Text with footnotes replaced and footnote list appended
    """
    # Pattern to match (src: LINK ) - captures the link part
    pattern = r'\(src:\s*([^)]+)\s*\)'
    
    # Find all matches
    matches = re.findall(pattern, text)
    
    if not matches:
        return text
    
    # Remove duplicates while preserving order
    unique_links = []
    seen = set()
    for link in matches:
        link = link.strip()
        if link not in seen:
            unique_links.append(link)
            seen.add(link)
    
    # Create a mapping from link to footnote number
    link_to_footnote = {link: i + 1 for i, link in enumerate(unique_links)}
    
    # Replace each occurrence with the appropriate footnote
    def replace_match(match):
        link = match.group(1).strip()
        footnote_num = link_to_footnote[link]
        return f'[^{footnote_num}]'
    
    # Replace all occurrences
    result_text = re.sub(pattern, replace_match, text)
    
    # Add footnote list at the end
    footnote_list = '\n\n'
    for link, num in link_to_footnote.items():
        footnote_list += f'[^{num}]: {link}\n'
    
    return result_text + footnote_list.rstrip()

In [10]:
import re

## Individual use cases

In [11]:
c = 0
memory["col1"] = memory["Purpose"] + " x "+ memory["Issue"]
for id in memory["id"].unique():
    c += 1
    txt = memory[memory["id"]==id]["Similar_use_case_detail"].values[0]
    UCID = memory[memory["id"]==id]["ZP_UC"].values[0].replace("-","").replace("_","")
    title = txt.split("\n")[0].strip("#").strip().replace(":"," ")
    table = memory[memory["id"]==id][["col1","Justification"]]
    print(id, UCID, title)
    MD = HEADER.replace("TITLE",title).replace("NAVORDER",str(c+4)).replace("PARENT",UCID)
    MD += "\n# "+title+"\n\n"+"# Evaluation\n\n"+table.to_markdown(index=False)+"\n\n# Executive summary"+convert_links_to_footnotes(txt).replace("# ", "## ")

    with open("docs/activities_"+id+".md", "w") as f:
        f.write(MD)

ZP_UCS--DUB-D-UC1_1 ZPUCSDUBDUC1 Living Lab BIPV (Building-Integrated Photovoltaics)
ZP_UCS--DUB-D-UC1_2 ZPUCSDUBDUC1 Ethos Engineering Living Lab Digital Twin
ZP_UCS--DUB-D-UC1_3 ZPUCSDUBDUC1 Integrated Energy Lab (IE Lab), UCD Energy Institute
ZP_UCS--DUB-D-UC1_4 ZPUCSDUBDUC1 Energy Living Lab (Provincia di Sassari, Italy)
ZP_UCS--DUB-D-UC1_5 ZPUCSDUBDUC1 Virtual Heating Plant Gleisdorf
ZP_UCS--PTO-B-UC1_1 ZPUCSPTOBUC1 Agra do Amial Renewable Energy Community
ZP_UCS--PTO-B-UC1_2 ZPUCSPTOBUC1 FUN Porto (Urban Forest and BioSpots Network)
ZP_UCS--PTO-B-UC1_3 ZPUCSPTOBUC1 LIFE-myBUILDINGisGREEN  Falcão Primary School Green Roof Demonstration
ZP_UCS--PTO-B-UC1_4 ZPUCSPTOBUC1 Porto di Mare Eco-District
ZP_UCS--PTO-B-UC1_5 ZPUCSPTOBUC1 Sponge Parks and Social Housing Energy Communities (EXHAUSTION Horizon Project)
ZP_UCS--MDC-B-UC1_1 ZPUCSMDCBUC1 Casa Sophia – Positive Energy Smart Home
ZP_UCS--MDC-B-UC1_2 ZPUCSMDCBUC1 Orcasitas Community Energy Renovation
ZP_UCS--MDC-B-UC1_3 ZPUCSMDCBUC1 HABITA-RES Urban Neighborhood Energy Visualization Tool
ZP_UCS--MDC-B-UC1_4 ZPUCSMDCBUC1 mySMARTLife – Smart City Lighthouse Project
ZP_UCS--MDC-B-UC1_5 ZPUCSMDCBUC1 Sharing Cities – Smart District Demonstration (Milan)
ZP_UCS--BRU-B-UC2_1 ZPUCSBRUBUC2 Tivoli GreenCity – The First Sustainable Neighbourhood in Brussels
ZP_UCS--BRU-B-UC2_2 ZPUCSBRUBUC2 GreenBizz Energy Community
ZP_UCS--BRU-B-UC2_3 ZPUCSBRUBUC2 Be.SHARE – Brussels Sustainable Heating and Renewable Energy Community
ZP_UCS--BRU-B-UC2_4 ZPUCSBRUBUC2 RESPONSE – integRatEd Solutions for POsitive eNergy and reSilient CitiEs
ZP_UCS--BRU-B-UC2_5 ZPUCSBRUBUC2 Sharing Cities – Smart Urban Energy Platform
ZP_UCS--DUB-D-UC4_1 ZPUCSDUBDUC4 SmartEnCity – Vitoria-Gasteiz Smart District
ZP_UCS--DUB-D-UC4_2 ZPUCSDUBDUC4 Dockline A3 BER Retrofit
ZP_UCS--DUB-D-UC4_3 ZPUCSDUBDUC4 EnergyVille Smart Building Living Lab
ZP_UCS--DUB-D-UC4_4 ZPUCSDUBDUC4 mySMARTLife Urban Digital Platform
ZP_UCS--DUB-D-UC4_5 ZPUCSDUBDUC4 IRIS Smart Cities – Positive Energy Districts
ZP_UCS--DUB-D-UC3_1 ZPUCSDUBDUC3 Amsterdam Smart Energy Grid
ZP_UCS--DUB-D-UC3_2 ZPUCSDUBDUC3 Aspern Smart City Research (ASCR)
ZP_UCS--DUB-D-UC3_3 ZPUCSDUBDUC3 Lyon Confluence Smart Community
ZP_UCS--DUB-D-UC3_4 ZPUCSDUBDUC3 REMOURBAN – Nottingham Lighthouse District
ZP_UCS--DUB-D-UC3_5 ZPUCSDUBDUC3 mySMARTLife – Hamburg Smart District
ZP_UCS--MGP-C-UC1_1 ZPUCSMGPCUC1 Madrid Nuevo Norte Urban Regeneration
ZP_UCS--MGP-C-UC1_2 ZPUCSMGPCUC1 Orcasitas Community Energy-Efficient Renovation
ZP_UCS--MGP-C-UC1_3 ZPUCSMGPCUC1 Lyon Confluence Smart District
ZP_UCS--MGP-C-UC1_4 ZPUCSMGPCUC1 Aspern Smart City Demonstration (Smarter Together)
ZP_UCS--MGP-C-UC1_5 ZPUCSMGPCUC1 Milan Porta Romana Sharing Cities (Horizon 2020  Sharing Cities)
ZP_UCS--AAR-A-UC3_1 ZPUCSAARAUC3 Green Hub House
ZP_UCS--AAR-A-UC3_2 ZPUCSAARAUC3 Lisbjerg Sustainable Neighborhood
ZP_UCS--AAR-A-UC3_3 ZPUCSAARAUC3 Spørring Circular Energy Park (CO-SHAPE Project)
ZP_UCS--AAR-A-UC3_4 ZPUCSAARAUC3 Madrid Nuevo Norte Green District (PROBONO Project Living Lab)
ZP_UCS--AAR-A-UC3_5 ZPUCSAARAUC3 Dublin Green Building Neighbourhood (PROBONO Project)
ZP_UCS--BRU-C-UC1_1 ZPUCSBRUCUC1 eHUBS – Smart Shared Green Mobility Hubs
ZP_UCS--BRU-C-UC1_2 ZPUCSBRUCUC1 Tivoli GreenCity Sustainable Neighbourhood
ZP_UCS--BRU-C-UC1_3 ZPUCSBRUCUC1 Green Corridor Project
ZP_UCS--BRU-C-UC1_4 ZPUCSBRUCUC1 10-Minute City Urban Planning Tool
ZP_UCS--BRU-C-UC1_5 ZPUCSBRUCUC1 Buildings as Material Banks (BAMB) – Circular Economy for Urban Development
ZP_UCS--MDC-C-UC1_1 ZPUCSMDCCUC1 Cleanwatts Living Lab – AI-Powered Renewable Energy Community
ZP_UCS--MDC-C-UC1_2 ZPUCSMDCCUC1 Energy Systems Catapult Living Lab
ZP_UCS--MDC-C-UC1_3 ZPUCSMDCCUC1 Living Lab for Testing Digital Energy Solutions at JRC Ispra
ZP_UCS--MDC-C-UC1_4 ZPUCSMDCCUC1 EU-DREAM  Effective Uptake of Digital Services to Repower European Consumers and Communities as Active Participants in Energy Transition and Markets
ZP_UCS--MDC-C-UC1_5 ZPUCSMDCCUC1 i-STENTORE Living Lab for Smart Energy Storage Deployment (Horizon Europe Project)
ZP_UCS--BRU-A-UC2_1 ZPUCSBRUAUC2 Tivoli GreenCity – The First Sustainable Neighbourhood in Brussels
ZP_UCS--BRU-A-UC2_2 ZPUCSBRUAUC2 Living Labs Brussels Retrofit Project
ZP_UCS--BRU-A-UC2_3 ZPUCSBRUAUC2 Waterschei Positive Energy Neighbourhood (oPEN Lab)
ZP_UCS--BRU-A-UC2_4 ZPUCSBRUAUC2 RESPONSE (integRatEd Solutions for POsitive eNergy and reSilient CitiEs)
ZP_UCS--BRU-A-UC2_5 ZPUCSBRUAUC2 oPEN Lab Positive Energy Neighbourhoods
ZP_UCS--AAR-A-UC4_1 ZPUCSAARAUC4 CO-SHAPE Circular Energy Park & Governance Innovation
ZP_UCS--AAR-A-UC4_2 ZPUCSAARAUC4 READY Project  Integrated Energy Retrofitting Demonstrator (READY Site Aarhus – Integrated Smart City Energy Solutions)
ZP_UCS--AAR-A-UC4_3 ZPUCSAARAUC4 Green Hub House – Experimental Urban and Climate-Friendly Community
ZP_UCS--AAR-A-UC4_4 ZPUCSAARAUC4 oPEN Lab – Positive Energy Neighbourhoods in Tartu, Pamplona, and Genk
ZP_UCS--AAR-A-UC4_5 ZPUCSAARAUC4 ARV – Climate Positive Circular Communities
ZP_UCS--DUB-C-UC3_1 ZPUCSDUBCUC3 ```
ZP_UCS--DUB-C-UC3_2 ZPUCSDUBCUC3 Cherrywood Urban Development – Barrington Building & TC1
ZP_UCS--DUB-C-UC3_3 ZPUCSDUBCUC3 Mapping Green Dublin – Community Engagement for Urban Trees
ZP_UCS--DUB-C-UC3_4 ZPUCSDUBCUC3 IGBC Biodiversity Case Study – National Forensic Mental Health Service (NFMHS) Project
ZP_UCS--DUB-C-UC3_5 ZPUCSDUBCUC3 mySMARTLife – Urban Data-Driven Sustainability Platform (Nantes, France)
ZP_UCS--MDC-A-UC1_1 ZPUCSMDCAUC1 Casa Sophia  Automating Spain’s Most Eco-Friendly Home
ZP_UCS--MDC-A-UC1_2 ZPUCSMDCAUC1 HABITA-RES  Energy Assessment and Refurbishment of Vulnerable Urban Areas
ZP_UCS--MDC-A-UC1_3 ZPUCSMDCAUC1 Energy-Efficient Renovation in Orcasitas with EPS Insulation
ZP_UCS--MDC-A-UC1_4 ZPUCSMDCAUC1 Staying Green  Madrid’s Urban Green Space Monitoring
ZP_UCS--MDC-A-UC1_5 ZPUCSMDCAUC1 Ampeers Energy Digital Twin for Districts (SMARTER TOGETHER Project)
ZP_UCS--MDC-A-UC1_6 ZPUCSMDCAUC1 CityLoops – Circular Construction and Demolition Waste Management
ZP_UCS--PRG-A-UC3_1 ZPUCSPRGAUC3 EDGE Olympic – Smart Climate Control and Air Quality Monitoring
ZP_UCS--MDC-D-UC1_1 ZPUCSMDCDUC1 oPEN Lab – Positive Energy Neighbourhoods in Tartu
ZP_UCS--MDC-D-UC1_2 ZPUCSMDCDUC1 UNCHAIN Project – Sustainable Urban Logistics and Low Emission Zones
ZP_UCS--MDC-D-UC1_3 ZPUCSMDCDUC1 ARV Project – Climate Positive Circular Communities
ZP_UCS--MDC-D-UC1_4 ZPUCSMDCDUC1 Smarter Together – Sustainable Urban Districts (Lyon)
ZP_UCS--MDC-D-UC1_5 ZPUCSMDCDUC1 mySMARTLife – Positive Energy Block Demonstration
ZP_UCS--DUB-A-UC3_1 ZPUCSDUBAUC3 Rediscovery Centre Ballymun (Dublin Boiler House Sustainability Education Centre)
ZP_UCS--DUB-A-UC3_2 ZPUCSDUBAUC3 Ella House High-Efficiency HVAC Retrofit
ZP_UCS--DUB-A-UC3_3 ZPUCSDUBAUC3 Tallaght District Heating Using Data Center Waste Heat
ZP_UCS--DUB-A-UC3_4 ZPUCSDUBAUC3 Dublin Docklands Green Heating Network
ZP_UCS--DUB-A-UC3_5 ZPUCSDUBAUC3 SmartEnCity – Vitoria-Gasteiz Green Neighborhood Retrofit
ZP_UCS--DUB-A-UC3_6 ZPUCSDUBAUC3 mySMARTLife Project – Nantes
ZP_UCS--DUB-B-UC3_1 ZPUCSDUBBUC3 Flexible Smart Charging for EVs (Amsterdam Smart Charging Pilot)
ZP_UCS--DUB-B-UC3_2 ZPUCSDUBBUC3 Seestadt Aspern Smart City District
ZP_UCS--DUB-B-UC3_3 ZPUCSDUBBUC3 EnergyLab Nordhavn (Nordhavn Smart Energy Living Lab)
ZP_UCS--DUB-B-UC3_4 ZPUCSDUBBUC3 SPARCS Espoo Positive Energy District
ZP_UCS--DUB-B-UC3_5 ZPUCSDUBBUC3 RESPONSE Dijon – Positive Energy Block
ZP_UCS--MGP-A-UC1_1 ZPUCSMGPAUC1 Triple – Eco-Carbon Neutral Co-Working and Event Space
ZP_UCS--MGP-B-UC3_1 ZPUCSMGPBUC3 Madrid Nuevo Norte Urban Geothermal Power Network
ZP_UCS--MGP-B-UC3_2 ZPUCSMGPBUC3 Móstoles Biomass District Heating Network
ZP_UCS--MGP-B-UC3_3 ZPUCSMGPBUC3 Manchester Civic Quarter Heat Network (CQHN)
ZP_UCS--MGP-B-UC3_4 ZPUCSMGPBUC3 UCM Complutense University District Heating Network Renovation
ZP_UCS--MGP-B-UC3_5 ZPUCSMGPBUC3 THERMOS Project  District Heating & Cooling Planning Tools (Horizon 2020)
ZP_UCS--MGP-B-UC3_6 ZPUCSMGPBUC3 3G to 5G District Heating and Cooling Networks (Horizon Europe)
ZP_UCS--PRG-A-UC4_1 ZPUCSPRGAUC4 Modřanský cukrovar Blue-Green District
ZP_UCS--PRG-A-UC4_2 ZPUCSPRGAUC4 Smíchov City – Comprehensive Urban Brownfield Redevelopment
ZP_UCS--PRG-A-UC4_3 ZPUCSPRGAUC4 City Green Court
ZP_UCS--PRG-A-UC4_4 ZPUCSPRGAUC4 Smart Kalasatama – Helsinki’s Digital and Sustainable District
ZP_UCS--PRG-A-UC4_5 ZPUCSPRGAUC4 SmartEnCity – Lighthouse District Smart Renovation (Vitoria-Gasteiz, Spain)
ZP_UCS--AAR-A-UC2_1 ZPUCSAARAUC2 Circle House – Denmark’s First Circular Social Housing Project
ZP_UCS--AAR-A-UC2_2 ZPUCSAARAUC2 Lisbjerg Sustainable Housing Development
ZP_UCS--AAR-A-UC2_3 ZPUCSAARAUC2 BIPED – Building Intelligent Positive Energy Districts
ZP_UCS--AAR-A-UC2_4 ZPUCSAARAUC2 The Dome – Green Community House (Domen)
ZP_UCS--AAR-A-UC2_5 ZPUCSAARAUC2 CO-SHAPE  Co-Shaping Areas in Peri-Urban Environments
ZP_UCS--BRU-B-UC1_1 ZPUCSBRUBUC1 Smart Kalasatama – Digital Energy Community Platform
ZP_UCS--BRU-B-UC1_2 ZPUCSBRUBUC1 Energent Energy Community Platform (Freiburg)
ZP_UCS--BRU-B-UC1_3 ZPUCSBRUBUC1 Sharing Cities – Digital Energy Platform
ZP_UCS--BRU-B-UC1_4 ZPUCSBRUBUC1 ATELIER  AmsTErdam and BiLbao cItizen drivEn smaRt cities
ZP_UCS--BRU-B-UC1_5 ZPUCSBRUBUC1 POCITYF – Positive Energy Blocks Digital Platform
ZP_UCS--PRG-A-UC1_1 ZPUCSPRGAUC1 Residential Building in Prague Monitors Energy Consumption via M-Bus
ZP_UCS--PRG-A-UC1_2 ZPUCSPRGAUC1 Prague Renewable Energy Community and Green Building Renovation
ZP_UCS--PRG-A-UC1_3 ZPUCSPRGAUC1 Energy Consumption Measurement Digitization – Smart Prague Initiative
ZP_UCS--PRG-A-UC1_4 ZPUCSPRGAUC1 ASCEND Smart Energy Neighborhood Demonstration
ZP_UCS--PRG-A-UC1_5 ZPUCSPRGAUC1 Enectiva  Cloud-Based Energy Monitoring for Green Buildings
ZP_UCS--MGP-C-UC3_1 ZPUCSMGPCUC3 Stockholm's Clean Vehicles Initiative
ZP_UCS--MGP-C-UC3_2 ZPUCSMGPCUC3 Smarter Together – Smart Mobility Solutions
ZP_UCS--MGP-C-UC3_3 ZPUCSMGPCUC3 CIVITAS ECCENTRIC – Electric Vehicle Monitoring and Optimization
ZP_UCS--MGP-C-UC3_4 ZPUCSMGPCUC3 GreenCharge – Incentivising Sustainable Urban Mobility
ZP_UCS--MGP-C-UC3_5 ZPUCSMGPCUC3 eHUBS – Smart Shared Mobility Hubs
ZP_UCS--DUB-C-UC4_1 ZPUCSDUBCUC4 ```
ZP_UCS--DUB-C-UC4_2 ZPUCSDUBCUC4 Aarhus Smart Building Elevator Usage Analytics
ZP_UCS--DUB-C-UC4_3 ZPUCSDUBCUC4 Brussels Green Building District Monitoring
ZP_UCS--DUB-C-UC4_4 ZPUCSDUBCUC4 ```
ZP_UCS--DUB-C-UC4_5 ZPUCSDUBCUC4 Porto Sustainable Neighbourhood Living Lab (PROBONO Horizon Project)
ZP_UCS--BRU-B-UC3_1 ZPUCSBRUBUC3 Savonnerie Heymans  A Former Soap Factory Turned Into a Sustainable Housing Project
ZP_UCS--BRU-B-UC3_2 ZPUCSBRUBUC3 Tivoli GreenCity
ZP_UCS--BRU-B-UC3_3 ZPUCSBRUBUC3 GreenBizz Energy Community
ZP_UCS--BRU-B-UC3_4 ZPUCSBRUBUC3 RESPONSE Project – Positive Energy Neighbourhoods
ZP_UCS--BRU-B-UC3_5 ZPUCSBRUBUC3 Buildings as Material Banks (BAMB)
ZP_UCS--DUB-C-UC5_1 ZPUCSDUBCUC5 I-CHANGE Milan Living Lab
ZP_UCS--DUB-C-UC5_2 ZPUCSDUBCUC5 Trinity College Dublin Living Lab – Air Quality Monitoring
ZP_UCS--DUB-C-UC5_3 ZPUCSDUBCUC5 SCORE Coastal City Living Lab – Rotterdam
ZP_UCS--DUB-C-UC5_4 ZPUCSDUBCUC5 ```
ZP_UCS--DUB-C-UC5_5 ZPUCSDUBCUC5 mySMARTLife  Urban Data Platform for Smart City Management
ZP_UCS--PTO-B-UC2_1 ZPUCSPTOBUC2 Agra do Amial Renewable Energy Community
ZP_UCS--PTO-B-UC2_2 ZPUCSPTOBUC2 FUN Porto – Urban Native Forest Initiative
ZP_UCS--PTO-B-UC2_3 ZPUCSPTOBUC2 ```
ZP_UCS--PTO-B-UC2_4 ZPUCSPTOBUC2 The Fifth Façade Project – Praça de Lisboa Olive Grove Green Roof
ZP_UCS--PTO-B-UC2_5 ZPUCSPTOBUC2 Social Green – Green Renovation for Social Housing (Interreg Europe)
ZP_UCS--DUB-C-UC2_1 ZPUCSDUBCUC2 People-Counting Sensors  Enhancing Building Efficiency with GDPR Compliance at TU Dublin
ZP_UCS--DUB-C-UC2_2 ZPUCSDUBCUC2 Ethos Engineering Living Lab
ZP_UCS--DUB-C-UC2_3 ZPUCSDUBCUC2 Hub Criativo do Beato Living Lab
ZP_UCS--DUB-C-UC2_4 ZPUCSDUBCUC2 The Edge Amsterdam  BREEAM-NL Smart Building Pilot
ZP_UCS--DUB-C-UC2_5 ZPUCSDUBCUC2 ```
ZP_UCS--BRU-A-UC1_1 ZPUCSBRUAUC1 Tivoli GreenCity Sustainable Neighbourhood
ZP_UCS--BRU-A-UC1_2 ZPUCSBRUAUC1 Buildings As Material Banks (BAMB)
ZP_UCS--BRU-A-UC1_3 ZPUCSBRUAUC1 Bridge City – Regenerative Development
ZP_UCS--BRU-A-UC1_4 ZPUCSBRUAUC1 Transforming Collectivity – Community Housing for Socially Empowered Living
ZP_UCS--BRU-A-UC1_5 ZPUCSBRUAUC1 Oxygen Office Building – BAMB Pilot (Horizon 2020 Project)
ZP_UCS--PTO-A-UC2_1 ZPUCSPTOAUC2 Agra do Amial Renewable Energy Community
ZP_UCS--PTO-A-UC2_2 ZPUCSPTOAUC2 FUN Porto Urban Forest & BioSpots Network
ZP_UCS--PTO-A-UC2_3 ZPUCSPTOAUC2 LIFE-myBUILDINGisGREEN Project  Falcão Primary School
ZP_UCS--PTO-A-UC2_4 ZPUCSPTOAUC2 Amsterdam Zuidoost Energy Community (ATELIER Project)
ZP_UCS--PTO-A-UC2_5 ZPUCSPTOAUC2 La Pinada Eco-Neighbourhood (MAKING-CITY)
ZP_UCS--DUB-A-UC4_1 ZPUCSDUBAUC4 Smart Waste Management Pilot – Jätkäsaari District, Helsinki
ZP_UCS--DUB-A-UC4_2 ZPUCSDUBAUC4 Barcelona Smart Waste City Project
ZP_UCS--DUB-A-UC4_3 ZPUCSDUBAUC4 Milan Door-to-Door Food Waste Collection Program
ZP_UCS--DUB-A-UC4_4 ZPUCSDUBAUC4 Circular South (Horizon 2020 Project)
ZP_UCS--DUB-A-UC4_5 ZPUCSDUBAUC4 SmartWaste – Smart Waste Management in Stavanger (Horizon 2020 Project)
ZP_UCS--DUB-A-UC1_1 ZPUCSDUBAUC1 Urban Sense  Monitoring Greenhouse Gas Emissions in Real Time Across Dublin
ZP_UCS--DUB-A-UC1_2 ZPUCSDUBAUC1 Public Building Energy Monitoring at Wood Quay Civic Offices
ZP_UCS--DUB-A-UC1_3 ZPUCSDUBAUC1 Dublin City Air and Noise Monitoring Initiative
ZP_UCS--DUB-A-UC1_4 ZPUCSDUBAUC1 Smart Green Roof Monitoring Project
ZP_UCS--DUB-A-UC1_5 ZPUCSDUBAUC1 IRIS Smart Cities – Utrecht Lighthouse Demonstration
ZP_UCS--DUB-A-UC1_6 ZPUCSDUBAUC1 Sharing Cities – Smart Building Neighborhood Monitoring (Milan, Italy)
ZP_UCS--BRU-A-UC3_1 ZPUCSBRUAUC3 Tivoli GreenCity – The First Sustainable Neighbourhood in Brussels
ZP_UCS--BRU-A-UC3_2 ZPUCSBRUAUC3 Smart Kalasatama District
ZP_UCS--BRU-A-UC3_3 ZPUCSBRUAUC3 Aspern Smart City Research (ASCR)
ZP_UCS--BRU-A-UC3_4 ZPUCSBRUAUC3 Amsterdam Smart Energy Neighborhoods (ATELIER Project)
ZP_UCS--BRU-A-UC3_5 ZPUCSBRUAUC3 Lyon Confluence Smart Neighborhood (Smarter Together)
ZP_UCS--MGP-C-UC2_1 ZPUCSMGPCUC2 Smart EV Charging and District Energy Optimization in Buiksloterham
ZP_UCS--MGP-C-UC2_2 ZPUCSMGPCUC2 Natural Wood in Affordable Housing at the Puente de Vallecas Eco-Neighborhood (SFJ6 Project)
ZP_UCS--MGP-C-UC2_3 ZPUCSMGPCUC2 Madrid Nuevo Norte Sustainable Urban Development
ZP_UCS--MGP-C-UC2_4 ZPUCSMGPCUC2 SRI4Cities – Smart Readiness Indicator Demonstration in Vienna
ZP_UCS--MGP-C-UC2_5 ZPUCSMGPCUC2 Sharing Cities – Integrated Smart Energy Solutions in Porta Romana-Vettabbia, Milan
ZP_UCS--MGP-B-UC2_1 ZPUCSMGPBUC2 Manchester Civic Quarter Heat Network
ZP_UCS--MGP-B-UC2_2 ZPUCSMGPBUC2 Districlima  Barcelona District Heating and Cooling Network (Forum and 22@ Districts)
ZP_UCS--MGP-B-UC2_3 ZPUCSMGPBUC2 Barrio La Pinada District Heating & Cooling Network
ZP_UCS--MGP-B-UC2_4 ZPUCSMGPBUC2 FLEXYNETS – Intelligent District Heating and Cooling Networks
ZP_UCS--MGP-B-UC2_5 ZPUCSMGPBUC2 3G to 5G District Heating and Cooling Networks (NetZeroCities / Horizon Project)
ZP_UCS--AAR-A-UC1_1 ZPUCSAARAUC1 TRÆ – Tall Timber Office Building
ZP_UCS--AAR-A-UC1_2 ZPUCSAARAUC1 Lisbjerg – Sustainable Neighborhood in Aarhus
ZP_UCS--AAR-A-UC1_3 ZPUCSAARAUC1 AARhus by BIG – Green Courtyard Residential Complex
ZP_UCS--AAR-A-UC1_4 ZPUCSAARAUC1 Spørring Circular Energy Park – CO-SHAPE Project
ZP_UCS--AAR-A-UC1_5 ZPUCSAARAUC1 BIPED – Building Intelligent Positive Energy Districts
ZP_UCS--AAR-B-UC1_1 ZPUCSAARBUC1 READY Project Demo Site – Aarhus
ZP_UCS--AAR-B-UC1_2 ZPUCSAARBUC1 Lisbjerg – Sustainable Urban Development
ZP_UCS--AAR-B-UC1_3 ZPUCSAARBUC1 CO-SHAPE – Peri-Urban Circular Energy Hub
ZP_UCS--AAR-B-UC1_4 ZPUCSAARBUC1 Green Hub House – Urban Climate Living Lab
ZP_UCS--AAR-B-UC1_5 ZPUCSAARBUC1 Sharing Cities – Smart Green Neighbourhoods
ZP_UCS--AAR-B-UC1_6 ZPUCSAARBUC1 IRIS Smart Cities – Utrecht Demo Site (Horizon 2020 Project)
ZP_UCS--DUB-A-UC2_1 ZPUCSDUBAUC2 Amsterdam Smart Building Digital Twin (SRI Pilot)
ZP_UCS--DUB-A-UC2_2 ZPUCSDUBAUC2 Seestadt Aspern Smart City Digital Twin
ZP_UCS--DUB-A-UC2_3 ZPUCSDUBAUC2 Mapping Green Dublin
ZP_UCS--DUB-A-UC2_4 ZPUCSDUBAUC2 SmartEnCity  Integrated Smart Solutions for Urban Regeneration
ZP_UCS--DUB-A-UC2_5 ZPUCSDUBAUC2 Sharing Cities  Smart City Digital Twin for Neighborhood Sustainability
ZP_UCS--BRU-B-UC4_1 ZPUCSBRUBUC4 Tivoli GreenCity – Sustainable Neighbourhood Impact Evaluation
ZP_UCS--BRU-B-UC4_2 ZPUCSBRUBUC4 Buildings as Material Banks (BAMB) – Circular Building Digital Twins
ZP_UCS--BRU-B-UC4_3 ZPUCSBRUBUC4 Bridge City – Regenerative Urban Development
ZP_UCS--BRU-B-UC4_4 ZPUCSBRUBUC4 Sharing Cities  Interoperable Digital Twins for Smart Energy Neighbourhoods
ZP_UCS--BRU-B-UC4_5 ZPUCSBRUBUC4 mySMARTLife – Interconnected Smart Districts (Horizon 2020 Project)
ZP_UCS--PTO-A-UC1_1 ZPUCSPTOAUC1 Agra do Amial Renewable Energy Community
ZP_UCS--PTO-A-UC1_2 ZPUCSPTOAUC1 LIFE-myBUILDINGisGREEN  Falcão Primary School Green Roof
ZP_UCS--PTO-A-UC1_3 ZPUCSPTOAUC1 Praça de Lisboa Green Roof & Fifth Façade Project
ZP_UCS--PTO-A-UC1_4 ZPUCSPTOAUC1 Porto di Mare Eco-District (New European Bauhaus Project)
ZP_UCS--PTO-A-UC1_5 ZPUCSPTOAUC1 LIFE-myBUILDINGisGREEN  Horta das Figueiras School Green Roof
ZP_UCS--DUB-D-UC2_1 ZPUCSDUBDUC2 Cleanwatts Living Lab  AI-Powered Renewable Energy Communities
ZP_UCS--DUB-D-UC2_2 ZPUCSDUBDUC2 Ethos Engineering Living Lab
ZP_UCS--DUB-D-UC2_3 ZPUCSDUBDUC2 Living Lab BIPV - Helmholtz-Zentrum Berlin
ZP_UCS--DUB-D-UC2_4 ZPUCSDUBDUC2 DT-Enabled Residential IoT Microgrid Living Lab (IoT-MGLab)
ZP_UCS--DUB-D-UC2_5 ZPUCSDUBDUC2 SSE Airtricity Smart Homes Living Lab (EU-DREAM Project)
ZP_UCS--PRG-A-UC2_1 ZPUCSPRGAUC2 Smart Energy Management at De Ceuvel
ZP_UCS--MGP-B-UC1_1 ZPUCSMGPBUC1 Geothermal District Heating Network in Paris-Saclay
ZP_UCS--MGP-B-UC1_2 ZPUCSMGPBUC1 Høje Taastrup 4th Generation District Heating Network (4GDH)
ZP_UCS--MGP-B-UC1_3 ZPUCSMGPBUC1 Barrio La Pinada District Heating and Cooling Network
ZP_UCS--MGP-B-UC1_4 ZPUCSMGPBUC1 Heerlen Mijnwater 5th Generation District Heating and Cooling (D2Grids Project)
ZP_UCS--MGP-B-UC1_5 ZPUCSMGPBUC1 Vitoria-Gasteiz DHC Planning with the THERMOS Tool (Horizon 2020)
ZP_UCS--PTO-C-UC1_1 ZPUCSPTOCUC1 Agra do Amial Renewable Energy Community
ZP_UCS--PTO-C-UC1_2 ZPUCSPTOCUC1 Falcão Primary School Green Roofs – LIFE-myBUILDINGisGREEN
ZP_UCS--PTO-C-UC1_3 ZPUCSPTOCUC1 Praça de Lisboa Olive Grove Green Roof & Porto Fifth Façade Project
ZP_UCS--PTO-C-UC1_4 ZPUCSPTOCUC1 Lyon Confluence Smart District
ZP_UCS--PTO-C-UC1_5 ZPUCSPTOCUC1 H22 – The Making of a Smarter City
ZP_UCS--DUB-B-UC1_1 ZPUCSDUBBUC1 Zuidas Smart Mobility and EV Parking Management
ZP_UCS--DUB-B-UC1_2 ZPUCSDUBBUC1 eParkomat EV and Smart Parking System
ZP_UCS--DUB-B-UC1_3 ZPUCSDUBBUC1 Lyon Confluence Smart Mobility and Energy District
ZP_UCS--DUB-B-UC1_4 ZPUCSDUBBUC1 REMOURBAN  REgeneration MOdel for smart URBAN transformation (Nottingham Demonstrator)
ZP_UCS--DUB-B-UC1_5 ZPUCSDUBBUC1 Sharing Cities  Smart Parking and e-Mobility Pilot (Horizon 2020 Project)
ZP_UCS--DUB-B-UC2_1 ZPUCSDUBBUC2 Cleanwatts Living Lab  AI-powered Renewable Energy Communities
ZP_UCS--DUB-B-UC2_2 ZPUCSDUBBUC2 Open Thor Living Lab
ZP_UCS--DUB-B-UC2_3 ZPUCSDUBBUC2 IREN Living Lab  Energy Flexibility and Interoperability at the Residential Scale
ZP_UCS--DUB-B-UC2_4 ZPUCSDUBBUC2 Tallaght SmartGrid Testbed
ZP_UCS--DUB-B-UC2_5 ZPUCSDUBBUC2 SSE Airtricity Living Lab (EU DREAM Project)
ZP_UCS--DUB-C-UC1_1 ZPUCSDUBCUC1 Food Smart Schools Initiative
ZP_UCS--DUB-C-UC1_2 ZPUCSDUBCUC1 Smart Waste Reduction in Canteens (Gothenburg, Sweden)
ZP_UCS--DUB-C-UC1_3 ZPUCSDUBCUC1 Eco-Canteen Food Waste Management Initiative (Barcelona, Spain)

## Original Use cases

In [12]:
memory.head(2)

,FromProbono,Origin,Place,Type,Source,Justification,Purpose,Issue,Scale,Score,...,Source_Title,Reviewed,model,timestamp,reviewsrc,ZP_UC,Similar_use_case_number,Similar_use_case_detail,id,col1
0,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The Living Lab BIPV represents a pioneering in...,Attractiveness,"Innovation, creativity and research",Building,5,...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1,"Attractiveness x Innovation, creativity and re..."
1,False,open_web_review,TBC,Activity,# Living Lab BIPV (Building-Integrated Photovo...,The initiative focuses on reducing the environ...,Preservation and improvement of environment,Biodiversity and ecosystem services,Building,4,...,Building-integrated photovoltaics research ini...,False,gpt-4o-mini,"11/22/2025, 09:42:44",N/A,ZP_UCS--DUB-D-UC1,1,# Living Lab BIPV (Building-Integrated Photovo...,ZP_UCS--DUB-D-UC1_1,Preservation and improvement of environment x ...

In [ ]:
c = 5
for id in memory["ZP_UC"].unique():
    c += 1
    txt = df[df["Origin"]==id]["Source"].values[0]
    title = df[df["Origin"]==id]["Source_Title"].values[0].replace(":"," ")


    MD = HEADER.replace("TITLE",id.replace("-","").replace("_","")).replace("NAVORDER",str(c+4)).replace("\nparent: PARENT","")
    MD += "\n# "+str(id)+" : " +title+"\n\n"

    MD += "# Related use cases found online\n\n"
    for ix, row in memory[memory["ZP_UC"] == id].drop_duplicates(subset= ["Similar_use_case_detail"]).iterrows():
        titl = row["Similar_use_case_detail"].split("\n")[0].strip("#").strip()
        
        MD += "* ["+titl+"](activities_"+row["id"]+".md)\n"

    MD += "\n\n# Original text\n\n"+convert_links_to_footnotes(txt).replace("# ", "## ")

    with open("docs/uc_"+id+".md", "w") as f:
        f.write(MD)

NameError: name 'df' is not defined